import { defineSchema } from "convex/server";
import {
  usersTable,
  orgsTable,
  membershipsTable,
  servicesTable,
  orgServicesTable,
  profilesTable,
  requestsTable,
  eventsTable,
  documentsTable,
  postsTable,
  conversationsTable,
  formTemplatesTable,
  appointmentSlotsTable,
  appointmentsTable,
  messagesTable,
  documentTemplatesTable,
  paymentsTable,
  documentVerificationsTable,
  agentNotesTable,
  consularRegistrationsTable,
  cvTable,
  childProfilesTable,
  auditLogTable,
  notificationsTable,
  tutorialsTable,
  communityEventsTable,
} from "./schemas";

export default defineSchema({
  users: usersTable,
  orgs: orgsTable,
  memberships: membershipsTable,
  services: servicesTable,
  orgServices: orgServicesTable,
  profiles: profilesTable,
  requests: requestsTable,
  events: eventsTable,
  documents: documentsTable,
  posts: postsTable,
  conversations: conversationsTable,
  formTemplates: formTemplatesTable,
  appointmentSlots: appointmentSlotsTable,
  appointments: appointmentsTable,
  messages: messagesTable,
  documentTemplates: documentTemplatesTable,
  payments: paymentsTable,
  documentVerifications: documentVerificationsTable,
  agentNotes: agentNotesTable,
  consularRegistrations: consularRegistrationsTable,
  cv: cvTable,
  childProfiles: childProfilesTable,
  auditLog: auditLogTable,
  notifications: notificationsTable,
  tutorials: tutorialsTable,
  communityEvents: communityEventsTable,
});
