
export enum ServiceCategory {
  Identity = 'identity',
  Passport = 'passport',
  CivilStatus = 'civil_status',
  Visa = 'visa',
  Certification = 'certification',
  Transcript = 'transcript',
  Registration = 'registration',
  Assistance = 'assistance',
  TravelDocument = 'travel_document',
  Other = 'other',
}

export enum EmergencyContactType {
  Resident = 'resident',
  HomeLand = 'home_land',
}

export enum ServiceStatus {
  Active = 'active',
  Inactive = 'inactive',
  Suspended = 'suspended',
}

export enum RequestStatus {
  Pending = 'pending',
  PendingCompletion = 'pending_completion',
  Edited = 'edited',
  Draft = 'draft',
  Submitted = 'submitted',
  UnderReview = 'under_review',
  InProduction = 'in_production',
  Validated = 'validated',
  Rejected = 'rejected',
  ReadyForPickup = 'ready_for_pickup',
  AppointmentScheduled = 'appointment_scheduled',
  Completed = 'completed',
  Cancelled = 'cancelled',
}

export enum RequestPriority {
  Normal = 'normal',
  Urgent = 'urgent',
  Critical = 'critical',
}

export enum UserStatus {
  Active = 'active',
  Inactive = 'inactive',
  Suspended = 'suspended',
}

export enum UserRole {
  User = 'user',
  Agent = 'agent',
  Admin = 'admin',
  SuperAdmin = 'super_admin',
  Manager = 'manager',
  IntelAgent = 'intel_agent',
  EducationAgent = 'education_agent',
}

export enum MemberRole {
  Admin = 'admin',
  Agent = 'agent',
  Viewer = 'viewer',
}

export enum OrganizationType {
  Embassy = 'embassy',
  Consulate = 'consulate',
  GeneralConsulate = 'general_consulate',
  HonoraryConsulate = 'honorary_consulate',
  ThirdParty = 'third_party',
}

export enum DocumentStatus {
  Pending = 'pending',
  Validated = 'validated',
  Rejected = 'rejected',
  Expired = 'expired',
  Expiring = 'expiring',
}

export enum AppointmentStatus {
  Draft = 'draft',
  Pending = 'pending',
  Scheduled = 'scheduled',
  Confirmed = 'confirmed',
  Completed = 'completed',
  Cancelled = 'cancelled',
  Missed = 'missed',
  Rescheduled = 'rescheduled',
}

export enum NotificationStatus {
  Pending = 'pending',
  Sent = 'sent',
  Delivered = 'delivered',
  Failed = 'failed',
  Read = 'read',
}

export enum NotificationType {
  Updated = 'updated',
  Reminder = 'reminder',
  Confirmation = 'confirmation',
  Cancellation = 'cancellation',
  Communication = 'communication',
  ImportantCommunication = 'important_communication',
  AppointmentConfirmation = 'appointment_confirmation',
  AppointmentReminder = 'appointment_reminder',
  AppointmentCancellation = 'appointment_cancellation',
  ConsularRegistrationSubmitted = 'consular_registration_submitted',
  ConsularRegistrationValidated = 'consular_registration_validated',
  ConsularRegistrationRejected = 'consular_registration_rejected',
  ConsularCardReady = 'consular_card_ready',
  ConsularRegistrationCompleted = 'consular_registration_completed',
  Feedback = 'feedback',
}


export enum ProfileCategory {
  Adult = 'adult',
  Minor = 'minor',
}

export enum ProfileStatus {
  Draft = 'draft',
  Active = 'active',
  Inactive = 'inactive',
  Pending = 'pending',
  Suspended = 'suspended',
}

export enum OwnerType {
  User = 'user',
  Profile = 'profile',
  Organization = 'organization',
  Request = 'request',
  ChildProfile = 'child_profile',
}


export enum DocumentType {
  Passport = 'passport',
  BirthCertificate = 'birth_certificate',
  IdentityCard = 'identity_card',
  DriverLicense = 'driver_license',
  Photo = 'photo',
  ProofOfAddress = 'proof_of_address',
  FamilyBook = 'family_book',
  Other = 'other',
  MarriageCertificate = 'marriage_certificate',
  DivorceDecree = 'divorce_decree',
  NationalityCertificate = 'nationality_certificate',
  VisaPages = 'visa_pages',
  EmploymentProof = 'employment_proof',
  NaturalizationDecree = 'naturalization_decree',
  IdentityPhoto = 'identity_photo',
  ConsularCard = 'consular_card',
  DeathCertificate = 'death_certificate',
  ResidencePermit = 'residence_permit',
}


export enum AppointmentType {
  DocumentSubmission = 'document_submission',
  DocumentCollection = 'document_collection',
  Interview = 'interview',
  MarriageCeremony = 'marriage_ceremony',
  Emergency = 'emergency',
  Other = 'other',
  Consultation = 'consultation',
}

export enum ParticipantRole {
  Attendee = 'attendee',
  Agent = 'agent',
  Organizer = 'organizer',
}

export enum ParticipantStatus {
  Confirmed = 'confirmed',
  Tentative = 'tentative',
  Declined = 'declined',
}


export enum NotificationChannel {
  App = 'app',
  Email = 'email',
  Sms = 'sms',
}


export enum OrganizationStatus {
  Active = 'active',
  Inactive = 'inactive',
  Suspended = 'suspended',
}


export enum ActivityType {
  RequestCreated = 'request_created',
  RequestSubmitted = 'request_submitted',
  RequestAssigned = 'request_assigned',
  DocumentUploaded = 'document_uploaded',
  DocumentValidated = 'document_validated',
  DocumentDeleted = 'document_deleted',
  DocumentRejected = 'document_rejected',
  PaymentReceived = 'payment_received',
  RequestCompleted = 'request_completed',
  RequestCancelled = 'request_cancelled',
  CommentAdded = 'comment_added',
  StatusChanged = 'status_changed',
  ProfileUpdate = 'profile_update',
  AppointmentScheduled = 'appointment_scheduled',
  DocumentUpdated = 'document_updated',
  Assigned = 'assigned',
  NoteAdded = 'note_added',
  RegistrationRequested = 'registration_requested',
  ProfileCreated = 'profile_created',
}


export enum ValidationStatus {
  Pending = 'pending',
  Approved = 'approved',
  Rejected = 'rejected',
  RequiresReview = 'requires_review',
}


export enum RequestType {
  FirstRequest = 'first_request',
  Renewal = 'renewal',
  Modification = 'modification',
  ConsularRegistration = 'consular_registration',
  PassportRequest = 'passport_request',
  IdCardRequest = 'id_card_request',
}

export enum ProcessingMode {
  OnlineOnly = 'online_only',
  PresenceRequired = 'presence_required',
  Hybrid = 'hybrid',
  ByProxy = 'by_proxy',
}

export enum DeliveryMode {
  InPerson = 'in_person',
  Postal = 'postal',
  Electronic = 'electronic',
  ByProxy = 'by_proxy',
}

export enum DeliveryStatus {
  Requested = 'requested',
  Ready = 'ready',
  Pending = 'pending',
  Completed = 'completed',
  Cancelled = 'cancelled',
}

export enum Gender {
  Male = 'male',
  Female = 'female',
}

export enum MaritalStatus {
  Single = 'single',
  Married = 'married',
  Divorced = 'divorced',
  Widowed = 'widowed',
  CivilUnion = 'civil_union',
  Cohabiting = 'cohabiting',
}

export enum FamilyLink {
  Father = 'father',
  Mother = 'mother',
  Spouse = 'spouse',
  LegalGuardian = 'legal_guardian',
  Child = 'child',
  Other = 'other',
  BrotherSister = 'brother_sister',
}

export enum WorkStatus {
  SelfEmployed = 'self_employed',
  Employee = 'employee',
  Entrepreneur = 'entrepreneur',
  Unemployed = 'unemployed',
  Retired = 'retired',
  Student = 'student',
  Other = 'other',
}

export enum NationalityAcquisition {
  Birth = 'birth',
  Naturalization = 'naturalization',
  Marriage = 'marriage',
  Adoption = 'adoption',
  Other = 'other',
}

export enum NoteType {
  Internal = 'internal',
  Feedback = 'feedback',
}

export enum ParentalRole {
  Father = 'father',
  Mother = 'mother',
  LegalGuardian = 'legal_guardian',
}

export enum IntelligenceNoteType {
  PoliticalOpinion = 'political_opinion',
  Orientation = 'orientation',
  Associations = 'associations',
  TravelPatterns = 'travel_patterns',
  Contacts = 'contacts',
  Activities = 'activities',
  Other = 'other',
}

export enum IntelligenceNotePriority {
  Low = 'low',
  Medium = 'medium',
  High = 'high',
  Critical = 'critical',
}

export enum ConsularServiceType {
  PassportRequest = 'passport_request',
  ConsularCard = 'consular_card',
  BirthRegistration = 'birth_registration',
  MarriageRegistration = 'marriage_registration',
  DeathRegistration = 'death_registration',
  ConsularRegistration = 'consular_registration',
  NationalityCertificate = 'nationality_certificate',
}

export enum ServicePriority {
  Standard = 'standard',
  Urgent = 'urgent',
}

export enum ServiceStepType {
  Form = 'form',
  Documents = 'documents',
  Appointment = 'appointment',
  Payment = 'payment',
  Review = 'review',
  Delivery = 'delivery',
}

export enum RequestActionType {
  Assignment = 'assignment',
  StatusChange = 'status_change',
  NoteAdded = 'note_added',
  DocumentAdded = 'document_added',
  DocumentValidated = 'document_validated',
  AppointmentScheduled = 'appointment_scheduled',
  PaymentReceived = 'payment_received',
  Completed = 'completed',
  ProfileUpdate = 'profile_update',
  DocumentUpdated = 'document_updated',
  DocumentDeleted = 'document_deleted',
}

export enum FeedbackCategory {
  Bug = 'bug',
  Feature = 'feature',
  Improvement = 'improvement',
  Other = 'other',
}

export enum FeedbackStatus {
  Pending = 'pending',
  InReview = 'in_review',
  Resolved = 'resolved',
  Closed = 'closed',
}

export enum CountryStatus {
  Active = 'active',
  Inactive = 'inactive',
}

export enum EmailStatus {
  Pending = 'pending',
  Confirmed = 'confirmed',
  Unsubscribed = 'unsubscribed',
}

export enum UserPermission {
  ProfileRead = 'profile_read',
  ProfileWrite = 'profile_write',
  ProfileDelete = 'profile_delete',
  RequestRead = 'request_read',
  RequestWrite = 'request_write',
  RequestDelete = 'request_delete',
  DocumentRead = 'document_read',
  DocumentWrite = 'document_write',
  DocumentDelete = 'document_delete',
  AppointmentRead = 'appointment_read',
  AppointmentWrite = 'appointment_write',
  AppointmentDelete = 'appointment_delete',
  NotificationRead = 'notification_read',
  NotificationWrite = 'notification_write',
  NotificationDelete = 'notification_delete',
  AddressRead = 'address_read',
  AddressWrite = 'address_write',
  AddressDelete = 'address_delete',
  CountryRead = 'country_read',
  CountryWrite = 'country_write',
  CountryDelete = 'country_delete',
  EmergencyContactRead = 'emergency_contact_read',
  EmergencyContactWrite = 'emergency_contact_write',
  EmergencyContactDelete = 'emergency_contact_delete',
  FeedbackRead = 'feedback_read',
  FeedbackWrite = 'feedback_write',
  FeedbackDelete = 'feedback_delete',
  OrganizationRead = 'organization_read',
  OrganizationWrite = 'organization_write',
  OrganizationDelete = 'organization_delete',
  ServiceRead = 'service_read',
  ServiceWrite = 'service_write',
  ServiceDelete = 'service_delete',
  UserRead = 'user_read',
  UserWrite = 'user_write',
  UserDelete = 'user_delete',
}


export enum MigrationStatus {
  Pending = 'pending',
  Running = 'running',
  Completed = 'completed',
  Failed = 'failed',
  Cancelled = 'cancelled',
}

export enum MigrationType {
  Users = 'users',
  Organizations = 'organizations',
  Services = 'services',
  Requests = 'requests',
  Documents = 'documents',
  Appointments = 'appointments',
  Notifications = 'notifications',
  Addresses = 'addresses',
  Countries = 'countries',
  All = 'all',
}

export enum MembershipStatus {
  Active = 'active',
  Inactive = 'inactive',
  Suspended = 'suspended',
}


export enum ServiceFieldType {
  Text = 'text',
  Email = 'email',
  Phone = 'phone',
  Date = 'date',
  Select = 'select',
  Address = 'address',
  File = 'file',
  Checkbox = 'checkbox',
  Radio = 'radio',
  Textarea = 'textarea',
  Number = 'number',
  Document = 'document',
  Photo = 'photo',
}

export enum SelectType {
  Single = 'single',
  Multiple = 'multiple',
}

export enum CountryCode {
  AD = 'AD',
  AE = 'AE',
  AF = 'AF',
  AG = 'AG',
  AI = 'AI',
  AL = 'AL',
  AM = 'AM',
  AO = 'AO',
  AQ = 'AQ',
  AR = 'AR',
  AS = 'AS',
  AT = 'AT',
  AU = 'AU',
  AW = 'AW',
  AX = 'AX',
  AZ = 'AZ',
  BA = 'BA',
  BB = 'BB',
  BD = 'BD',
  BE = 'BE',
  BF = 'BF',
  BG = 'BG',
  BH = 'BH',
  BI = 'BI',
  BJ = 'BJ',
  BL = 'BL',
  BM = 'BM',
  BN = 'BN',
  BO = 'BO',
  BR = 'BR',
  BS = 'BS',
  BT = 'BT',
  BW = 'BW',
  BY = 'BY',
  BZ = 'BZ',
  CA = 'CA',
  CC = 'CC',
  CD = 'CD',
  CF = 'CF',
  CG = 'CG',
  CH = 'CH',
  CI = 'CI',
  CK = 'CK',
  CL = 'CL',
  CM = 'CM',
  CN = 'CN',
  CO = 'CO',
  CR = 'CR',
  CU = 'CU',
  CV = 'CV',
  CX = 'CX',
  CY = 'CY',
  CZ = 'CZ',
  DE = 'DE',
  DJ = 'DJ',
  DK = 'DK',
  DM = 'DM',
  DO = 'DO',
  DZ = 'DZ',
  EC = 'EC',
  EE = 'EE',
  EG = 'EG',
  ER = 'ER',
  ES = 'ES',
  ET = 'ET',
  FI = 'FI',
  FJ = 'FJ',
  FK = 'FK',
  FM = 'FM',
  FO = 'FO',
  FR = 'FR',
  GA = 'GA',
  GB = 'GB',
  GD = 'GD',
  GE = 'GE',
  GF = 'GF',
  GG = 'GG',
  GH = 'GH',
  GI = 'GI',
  GL = 'GL',
  GM = 'GM',
  GN = 'GN',
  GP = 'GP',
  GQ = 'GQ',
  GR = 'GR',
  GS = 'GS',
  GT = 'GT',
  GU = 'GU',
  GW = 'GW',
  GY = 'GY',
  HK = 'HK',
  HN = 'HN',
  HR = 'HR',
  HT = 'HT',
  HU = 'HU',
  ID = 'ID',
  IE = 'IE',
  IL = 'IL',
  IM = 'IM',
  IN = 'IN',
  IO = 'IO',
  IQ = 'IQ',
  IR = 'IR',
  IS = 'IS',
  IT = 'IT',
  JE = 'JE',
  JM = 'JM',
  JO = 'JO',
  JP = 'JP',
  KE = 'KE',
  KG = 'KG',
  KH = 'KH',
  KI = 'KI',
  KM = 'KM',
  KN = 'KN',
  KP = 'KP',
  KR = 'KR',
  KW = 'KW',
  KY = 'KY',
  KZ = 'KZ',
  LA = 'LA',
  LB = 'LB',
  LC = 'LC',
  LI = 'LI',
  LK = 'LK',
  LR = 'LR',
  LS = 'LS',
  LT = 'LT',
  LU = 'LU',
  LV = 'LV',
  LY = 'LY',
  MA = 'MA',
  MC = 'MC',
  MD = 'MD',
  ME = 'ME',
  MF = 'MF',
  MG = 'MG',
  MH = 'MH',
  MK = 'MK',
  ML = 'ML',
  MM = 'MM',
  MN = 'MN',
  MO = 'MO',
  MP = 'MP',
  MQ = 'MQ',
  MR = 'MR',
  MS = 'MS',
  MT = 'MT',
  MU = 'MU',
  MV = 'MV',
  MW = 'MW',
  MX = 'MX',
  MY = 'MY',
  MZ = 'MZ',
  NA = 'NA',
  NC = 'NC',
  NE = 'NE',
  NF = 'NF',
  NG = 'NG',
  NI = 'NI',
  NL = 'NL',
  NO = 'NO',
  NP = 'NP',
  NR = 'NR',
  NU = 'NU',
  NZ = 'NZ',
  OM = 'OM',
  PA = 'PA',
  PE = 'PE',
  PF = 'PF',
  PG = 'PG',
  PH = 'PH',
  PK = 'PK',
  PL = 'PL',
  PM = 'PM',
  PN = 'PN',
  PR = 'PR',
  PS = 'PS',
  PT = 'PT',
  PW = 'PW',
  PY = 'PY',
  QA = 'QA',
  RE = 'RE',
  RO = 'RO',
  RS = 'RS',
  RU = 'RU',
  RW = 'RW',
  SA = 'SA',
  SB = 'SB',
  SC = 'SC',
  SD = 'SD',
  SE = 'SE',
  SG = 'SG',
  SH = 'SH',
  SI = 'SI',
  SJ = 'SJ',
  SK = 'SK',
  SL = 'SL',
  SM = 'SM',
  SN = 'SN',
  SO = 'SO',
  SR = 'SR',
  SS = 'SS',
  ST = 'ST',
  SV = 'SV',
  SY = 'SY',
  SZ = 'SZ',
  TC = 'TC',
  TD = 'TD',
  TG = 'TG',
  TH = 'TH',
  TJ = 'TJ',
  TK = 'TK',
  TL = 'TL',
  TM = 'TM',
  TN = 'TN',
  TO = 'TO',
  TR = 'TR',
  TT = 'TT',
  TV = 'TV',
  TW = 'TW',
  TZ = 'TZ',
  UA = 'UA',
  UG = 'UG',
  US = 'US',
  UY = 'UY',
  UZ = 'UZ',
  VA = 'VA',
  VC = 'VC',
  VE = 'VE',
  VG = 'VG',
  VI = 'VI',
  VN = 'VN',
  VU = 'VU',
  WF = 'WF',
  WS = 'WS',
  YE = 'YE',
  YT = 'YT',
  ZA = 'ZA',
  ZM = 'ZM',
  ZW = 'ZW',
}

export const countryDialCodes = [
  { code: 'AD', dial_code: '376' },
  { code: 'AE', dial_code: '971' },
  { code: 'AF', dial_code: '93' },
  { code: 'AG', dial_code: '1268' },
  { code: 'AL', dial_code: '355' },
  { code: 'AM', dial_code: '374' },
  { code: 'AO', dial_code: '244' },
  { code: 'AR', dial_code: '54' },
  { code: 'AT', dial_code: '43' },
  { code: 'AU', dial_code: '61' },
  { code: 'AZ', dial_code: '994' },
  { code: 'BA', dial_code: '387' },
  { code: 'BB', dial_code: '1246' },
  { code: 'BD', dial_code: '880' },
  { code: 'BE', dial_code: '32' },
  { code: 'BF', dial_code: '226' },
  { code: 'BG', dial_code: '359' },
  { code: 'BH', dial_code: '973' },
  { code: 'BI', dial_code: '257' },
  { code: 'BJ', dial_code: '229' },
  { code: 'BN', dial_code: '673' },
  { code: 'BO', dial_code: '591' },
  { code: 'BR', dial_code: '55' },
  { code: 'BS', dial_code: '1242' },
  { code: 'BT', dial_code: '975' },
  { code: 'BW', dial_code: '267' },
  { code: 'BY', dial_code: '375' },
  { code: 'BZ', dial_code: '501' },
  { code: 'CA', dial_code: '1' },
  { code: 'CD', dial_code: '243' },
  { code: 'CF', dial_code: '236' },
  { code: 'CG', dial_code: '242' },
  { code: 'CH', dial_code: '41' },
  { code: 'CI', dial_code: '225' },
  { code: 'CL', dial_code: '56' },
  { code: 'CM', dial_code: '237' },
  { code: 'CN', dial_code: '86' },
  { code: 'CO', dial_code: '57' },
  { code: 'CR', dial_code: '506' },
  { code: 'CU', dial_code: '53' },
  { code: 'CV', dial_code: '238' },
  { code: 'CY', dial_code: '357' },
  { code: 'CZ', dial_code: '420' },
  { code: 'DE', dial_code: '49' },
  { code: 'DJ', dial_code: '253' },
  { code: 'DK', dial_code: '45' },
  { code: 'DM', dial_code: '1767' },
  { code: 'DO', dial_code: '1809' },
  { code: 'DZ', dial_code: '213' },
  { code: 'EC', dial_code: '593' },
  { code: 'EE', dial_code: '372' },
  { code: 'EG', dial_code: '20' },
  { code: 'ER', dial_code: '291' },
  { code: 'ES', dial_code: '34' },
  { code: 'ET', dial_code: '251' },
  { code: 'FI', dial_code: '358' },
  { code: 'FJ', dial_code: '679' },
  { code: 'FR', dial_code: '33' },
  { code: 'GA', dial_code: '241' },
  { code: 'GB', dial_code: '44' },
  { code: 'GD', dial_code: '1473' },
  { code: 'GE', dial_code: '995' },
  { code: 'GH', dial_code: '233' },
  { code: 'GM', dial_code: '220' },
  { code: 'GN', dial_code: '224' },
  { code: 'GQ', dial_code: '240' },
  { code: 'GR', dial_code: '30' },
  { code: 'GT', dial_code: '502' },
  { code: 'GW', dial_code: '245' },
  { code: 'GY', dial_code: '592' },
  { code: 'HK', dial_code: '852' },
  { code: 'HN', dial_code: '504' },
  { code: 'HR', dial_code: '385' },
  { code: 'HT', dial_code: '509' },
  { code: 'HU', dial_code: '36' },
  { code: 'ID', dial_code: '62' },
  { code: 'IE', dial_code: '353' },
  { code: 'IL', dial_code: '972' },
  { code: 'IM', dial_code: '44' },
  { code: 'IN', dial_code: '91' },
  { code: 'IO', dial_code: '246' },
  { code: 'IQ', dial_code: '964' },
  { code: 'IR', dial_code: '98' },
  { code: 'IS', dial_code: '354' },
  { code: 'IT', dial_code: '39' },
  { code: 'JE', dial_code: '44' },
  { code: 'JM', dial_code: '1876' },
  { code: 'JO', dial_code: '962' },
  { code: 'JP', dial_code: '81' },
  { code: 'KE', dial_code: '254' },
  { code: 'KG', dial_code: '996' },
  { code: 'KH', dial_code: '855' },
  { code: 'KI', dial_code: '686' },
  { code: 'KM', dial_code: '269' },
  { code: 'KN', dial_code: '1869' },
  { code: 'KP', dial_code: '850' },
  { code: 'KR', dial_code: '82' },
  { code: 'KW', dial_code: '965' },
  { code: 'KY', dial_code: '1345' },
  { code: 'KZ', dial_code: '7' },
  { code: 'LA', dial_code: '856' },
  { code: 'LB', dial_code: '961' },
  { code: 'LC', dial_code: '1758' },
  { code: 'LI', dial_code: '423' },
  { code: 'LK', dial_code: '94' },
  { code: 'LR', dial_code: '231' },
  { code: 'LS', dial_code: '266' },
  { code: 'LT', dial_code: '370' },
  { code: 'LU', dial_code: '352' },
  { code: 'LV', dial_code: '371' },
  { code: 'LY', dial_code: '218' },
  { code: 'MA', dial_code: '212' },
  { code: 'MC', dial_code: '377' },
  { code: 'MD', dial_code: '373' },
  { code: 'ME', dial_code: '382' },
  { code: 'MF', dial_code: '590' },
  { code: 'MG', dial_code: '261' },
  { code: 'MH', dial_code: '692' },
  { code: 'MK', dial_code: '389' },
  { code: 'ML', dial_code: '223' },
  { code: 'MM', dial_code: '95' },
  { code: 'MN', dial_code: '976' },
  { code: 'MO', dial_code: '853' },
  { code: 'MP', dial_code: '1670' },
  { code: 'MQ', dial_code: '596' },
  { code: 'MR', dial_code: '222' },
  { code: 'MS', dial_code: '1664' },
  { code: 'MT', dial_code: '356' },
  { code: 'MU', dial_code: '230' },
  { code: 'MV', dial_code: '960' },
  { code: 'MW', dial_code: '265' },
  { code: 'MX', dial_code: '52' },
  { code: 'MY', dial_code: '60' },
  { code: 'MZ', dial_code: '258' },
  { code: 'NA', dial_code: '264' },
  { code: 'NC', dial_code: '687' },
  { code: 'NE', dial_code: '227' },
  { code: 'NF', dial_code: '672' },
  { code: 'NG', dial_code: '234' },
  { code: 'NI', dial_code: '505' },
  { code: 'NL', dial_code: '31' },
  { code: 'NO', dial_code: '47' },
  { code: 'NP', dial_code: '977' },
  { code: 'NR', dial_code: '674' },
  { code: 'NU', dial_code: '683' },
  { code: 'NZ', dial_code: '64' },
  { code: 'OM', dial_code: '968' },
  { code: 'PA', dial_code: '507' },
  { code: 'PE', dial_code: '51' },
  { code: 'PF', dial_code: '689' },
  { code: 'PG', dial_code: '675' },
  { code: 'PH', dial_code: '63' },
  { code: 'PK', dial_code: '92' },
  { code: 'PL', dial_code: '48' },
  { code: 'PM', dial_code: '508' },
  { code: 'PN', dial_code: '870' },
  { code: 'PR', dial_code: '1' },
  { code: 'PS', dial_code: '970' },
  { code: 'PT', dial_code: '351' },
  { code: 'PW', dial_code: '680' },
  { code: 'PY', dial_code: '595' },
  { code: 'QA', dial_code: '974' },
  { code: 'RE', dial_code: '262' },
  { code: 'RO', dial_code: '40' },
  { code: 'RS', dial_code: '381' },
  { code: 'RU', dial_code: '7' },
  { code: 'RW', dial_code: '250' },
  { code: 'SA', dial_code: '966' },
  { code: 'SB', dial_code: '677' },
  { code: 'SC', dial_code: '248' },
  { code: 'SD', dial_code: '249' },
  { code: 'SE', dial_code: '46' },
  { code: 'SG', dial_code: '65' },
  { code: 'SH', dial_code: '290' },
  { code: 'SI', dial_code: '386' },
  { code: 'SJ', dial_code: '47' },
  { code: 'SK', dial_code: '421' },
  { code: 'SL', dial_code: '232' },
  { code: 'SM', dial_code: '378' },
  { code: 'SN', dial_code: '221' },
  { code: 'SO', dial_code: '252' },
  { code: 'SR', dial_code: '597' },
  { code: 'SS', dial_code: '211' },
  { code: 'ST', dial_code: '239' },
  { code: 'SV', dial_code: '503' },
  { code: 'SY', dial_code: '963' },
  { code: 'SZ', dial_code: '268' },
  { code: 'TC', dial_code: '1649' },
  { code: 'TD', dial_code: '235' },
  { code: 'TG', dial_code: '228' },
  { code: 'TH', dial_code: '66' },
  { code: 'TJ', dial_code: '992' },
  { code: 'TK', dial_code: '690' },
  { code: 'TL', dial_code: '670' },
  { code: 'TM', dial_code: '993' },
  { code: 'TN', dial_code: '216' },
  { code: 'TO', dial_code: '676' },
  { code: 'TR', dial_code: '90' },
  { code: 'TT', dial_code: '1868' },
  { code: 'TV', dial_code: '688' },
  { code: 'TW', dial_code: '886' },
  { code: 'TZ', dial_code: '255' },
  { code: 'UA', dial_code: '380' },
  { code: 'UG', dial_code: '256' },
  { code: 'US', dial_code: '1' },
  { code: 'UY', dial_code: '598' },
  { code: 'UZ', dial_code: '998' },
  { code: 'VA', dial_code: '39' },
  { code: 'VC', dial_code: '1784' },
  { code: 'VE', dial_code: '58' },
  { code: 'VG', dial_code: '1284' },
  { code: 'VI', dial_code: '1340' },
  { code: 'VN', dial_code: '84' },
  { code: 'VU', dial_code: '678' },
  { code: 'WF', dial_code: '681' },
  { code: 'WS', dial_code: '685' },
  { code: 'YE', dial_code: '967' },
  { code: 'YT', dial_code: '262' },
  { code: 'ZA', dial_code: '27' },
  { code: 'ZM', dial_code: '260' },
  { code: 'ZW', dial_code: '263' },
];

export const countryCodes = Object.values(CountryCode);
