// Barrel export for all schema tables
export { usersTable } from "./users";
export { orgsTable } from "./orgs";
export { membershipsTable } from "./memberships";
export { servicesTable } from "./services";
export { orgServicesTable } from "./orgServices";
export { profilesTable } from "./profiles";
export { requestsTable } from "./requests";
export { eventsTable } from "./events";
export { documentsTable } from "./documents";
export { postsTable } from "./posts";
export { conversationsTable } from "./conversations";
export { formTemplatesTable } from "./formTemplates";
export { appointmentSlotsTable, appointmentsTable } from "./appointments";
export { messagesTable } from "./messages";
export { documentTemplatesTable } from "./documentTemplates";
export { paymentsTable } from "./payments";
export { documentVerificationsTable } from "./documentVerifications";
export { agentNotesTable } from "./agentNotes";
export { consularRegistrationsTable } from "./consularRegistrations";
