import countries from '@/i18n/messages/fr/countries';

export type CountryCode = keyof typeof countries;
export const CountryCodeEnum = Object.keys(countries) as CountryCode[];

export const countryKeys = Object.keys(countries) as CountryCode[];

export const phoneCountries = [
  { value: '+213', countryCode: 'DZ' },
  { value: '+49', countryCode: 'DE' },
  { value: '+244', countryCode: 'AO' },
  { value: '+54', countryCode: 'AR' },
  { value: '+374', countryCode: 'AM' },
  { value: '+61', countryCode: 'AU' },
  { value: '+43', countryCode: 'AT' },
  { value: '+994', countryCode: 'AZ' },
  { value: '+973', countryCode: 'BH' },
  { value: '+880', countryCode: 'BD' },
  { value: '+32', countryCode: 'BE' },
  { value: '+229', countryCode: 'BJ' },
  { value: '+375', countryCode: 'BY' },
  { value: '+591', countryCode: 'BO' },
  { value: '+387', countryCode: 'BA' },
  { value: '+55', countryCode: 'BR' },
  { value: '+359', countryCode: 'BG' },
  { value: '+226', countryCode: 'BF' },
  { value: '+257', countryCode: 'BI' },
  { value: '+855', countryCode: 'KH' },
  { value: '+237', countryCode: 'CM' },
  { value: '+1', countryCode: 'CA' },
  { value: '+238', countryCode: 'CV' },
  { value: '+56', countryCode: 'CL' },
  { value: '+86', countryCode: 'CN' },
  { value: '+357', countryCode: 'CY' },
  { value: '+57', countryCode: 'CO' },
  { value: '+242', countryCode: 'CG' },
  { value: '+243', countryCode: 'CD' },
  { value: '+506', countryCode: 'CR' },
  { value: '+225', countryCode: 'CI' },
  { value: '+385', countryCode: 'HR' },
  { value: '+53', countryCode: 'CU' },
  { value: '+45', countryCode: 'DK' },
  { value: '+253', countryCode: 'DJ' },
  { value: '+20', countryCode: 'EG' },
  { value: '+971', countryCode: 'AE' },
  { value: '+593', countryCode: 'EC' },
  { value: '+291', countryCode: 'ER' },
  { value: '+34', countryCode: 'ES' },
  { value: '+372', countryCode: 'EE' },
  { value: '+1', countryCode: 'US' },
  { value: '+251', countryCode: 'ET' },
  { value: '+679', countryCode: 'FJ' },
  { value: '+358', countryCode: 'FI' },
  { value: '+33', countryCode: 'FR' },
  { value: '+241', countryCode: 'GA' },
  { value: '+220', countryCode: 'GM' },
  { value: '+995', countryCode: 'GE' },
  { value: '+233', countryCode: 'GH' },
  { value: '+30', countryCode: 'GR' },
  { value: '+502', countryCode: 'GT' },
  { value: '+224', countryCode: 'GN' },
  { value: '+245', countryCode: 'GW' },
  { value: '+240', countryCode: 'GQ' },
  { value: '+509', countryCode: 'HT' },
  { value: '+504', countryCode: 'HN' },
  { value: '+852', countryCode: 'HK' },
  { value: '+36', countryCode: 'HU' },
  { value: '+91', countryCode: 'IN' },
  { value: '+62', countryCode: 'ID' },
  { value: '+98', countryCode: 'IR' },
  { value: '+964', countryCode: 'IQ' },
  { value: '+353', countryCode: 'IE' },
  { value: '+354', countryCode: 'IS' },
  { value: '+972', countryCode: 'IL' },
  { value: '+39', countryCode: 'IT' },
  { value: '+81', countryCode: 'JP' },
  { value: '+962', countryCode: 'JO' },
  { value: '+7', countryCode: 'KZ' },
  { value: '+254', countryCode: 'KE' },
  { value: '+965', countryCode: 'KW' },
  { value: '+371', countryCode: 'LV' },
  { value: '+961', countryCode: 'LB' },
  { value: '+231', countryCode: 'LR' },
  { value: '+218', countryCode: 'LY' },
  { value: '+370', countryCode: 'LT' },
  { value: '+352', countryCode: 'LU' },
  { value: '+261', countryCode: 'MG' },
  { value: '+265', countryCode: 'MW' },
  { value: '+223', countryCode: 'ML' },
  { value: '+356', countryCode: 'MT' },
  { value: '+212', countryCode: 'MA' },
  { value: '+230', countryCode: 'MU' },
  { value: '+222', countryCode: 'MR' },
  { value: '+52', countryCode: 'MX' },
  { value: '+373', countryCode: 'MD' },
  { value: '+377', countryCode: 'MC' },
  { value: '+976', countryCode: 'MN' },
  { value: '+382', countryCode: 'ME' },
  { value: '+258', countryCode: 'MZ' },
  { value: '+264', countryCode: 'NA' },
  { value: '+31', countryCode: 'NL' },
  { value: '+64', countryCode: 'NZ' },
  { value: '+505', countryCode: 'NI' },
  { value: '+227', countryCode: 'NE' },
  { value: '+234', countryCode: 'NG' },
  { value: '+47', countryCode: 'NO' },
  { value: '+968', countryCode: 'OM' },
  { value: '+92', countryCode: 'PK' },
  { value: '+507', countryCode: 'PA' },
  { value: '+595', countryCode: 'PY' },
  { value: '+51', countryCode: 'PE' },
  { value: '+63', countryCode: 'PH' },
  { value: '+48', countryCode: 'PL' },
  { value: '+351', countryCode: 'PT' },
  { value: '+974', countryCode: 'QA' },
  { value: '+40', countryCode: 'RO' },
  { value: '+7', countryCode: 'RU' },
  { value: '+250', countryCode: 'RW' },
  { value: '+966', countryCode: 'SA' },
  { value: '+221', countryCode: 'SN' },
  { value: '+381', countryCode: 'RS' },
  { value: '+232', countryCode: 'SL' },
  { value: '+65', countryCode: 'SG' },
  { value: '+421', countryCode: 'SK' },
  { value: '+386', countryCode: 'SI' },
  { value: '+252', countryCode: 'SO' },
  { value: '+249', countryCode: 'SD' },
  { value: '+211', countryCode: 'SS' },
  { value: '+46', countryCode: 'SE' },
  { value: '+41', countryCode: 'CH' },
  { value: '+963', countryCode: 'SY' },
  { value: '+255', countryCode: 'TZ' },
  { value: '+235', countryCode: 'TD' },
  { value: '+66', countryCode: 'TH' },
  { value: '+228', countryCode: 'TG' },
  { value: '+216', countryCode: 'TN' },
  { value: '+90', countryCode: 'TR' },
  { value: '+380', countryCode: 'UA' },
  { value: '+44', countryCode: 'GB' },
  { value: '+598', countryCode: 'UY' },
  { value: '+58', countryCode: 'VE' },
  { value: '+84', countryCode: 'VN' },
  { value: '+263', countryCode: 'ZW' },
  { value: '+260', countryCode: 'ZM' },
  { value: '+590', countryCode: 'GP' },
  { value: '+594', countryCode: 'GF' },
  { value: '+596', countryCode: 'MQ' },
  { value: '+262', countryCode: 'RE' },
  { value: '+508', countryCode: 'BL' },
  { value: '+681', countryCode: 'WF' },
  { value: '+687', countryCode: 'NC' },
  { value: '+689', countryCode: 'PF' },
] as const;

export type CountryIndicator = (typeof phoneCountries)[number]['value'];
export const countryIndicators = phoneCountries.map(
  ({ value }) => value,
) as CountryIndicator[];

export const getCountryCode = (
  countryCode: CountryCode,
): CountryIndicator | undefined => {
  const country = phoneCountries.find((c) => c.countryCode === countryCode);
  return country?.value;
};
