/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as PostLoginRedirectRouteImport } from './routes/post-login-redirect'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as InformationRouteImport } from './routes/information'
import { Route as FormulairesRouteImport } from './routes/formulaires'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AccessibiliteRouteImport } from './routes/accessibilite'
import { Route as MySpaceRouteRouteImport } from './routes/my-space/route'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as OrgsIndexRouteImport } from './routes/orgs/index'
import { Route as NewsIndexRouteImport } from './routes/news/index'
import { Route as MySpaceIndexRouteImport } from './routes/my-space/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AcademyIndexRouteImport } from './routes/academy/index'
import { Route as VerifyTokenRouteImport } from './routes/verify.$token'
import { Route as SignUpSplatRouteImport } from './routes/sign-up/$'
import { Route as SignInSplatRouteImport } from './routes/sign-in/$'
import { Route as ServicesSlugRouteImport } from './routes/services/$slug'
import { Route as OrgsSlugRouteImport } from './routes/orgs/$slug'
import { Route as NewsSlugRouteImport } from './routes/news/$slug'
import { Route as MySpaceVaultRouteImport } from './routes/my-space/vault'
import { Route as MySpaceSettingsRouteImport } from './routes/my-space/settings'
import { Route as MySpaceRequestsRouteImport } from './routes/my-space/requests'
import { Route as MySpaceNotificationsRouteImport } from './routes/my-space/notifications'
import { Route as MySpaceIboiteRouteImport } from './routes/my-space/iboite'
import { Route as MySpaceCvRouteImport } from './routes/my-space/cv'
import { Route as MySpaceCompaniesRouteImport } from './routes/my-space/companies'
import { Route as MySpaceChildrenRouteImport } from './routes/my-space/children'
import { Route as MySpaceAssociationsRouteImport } from './routes/my-space/associations'
import { Route as DashboardAssociationClaimsRouteImport } from './routes/dashboard/association-claims'
import { Route as AdminStatisticsRouteImport } from './routes/admin/statistics'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AcademySlugRouteImport } from './routes/academy/$slug'
import { Route as MySpaceServicesIndexRouteImport } from './routes/my-space/services/index'
import { Route as MySpaceProfileIndexRouteImport } from './routes/my-space/profile/index'
import { Route as MySpaceAppointmentsIndexRouteImport } from './routes/my-space/appointments/index'
import { Route as DashboardUsersIndexRouteImport } from './routes/dashboard/users/index'
import { Route as DashboardTutorialsIndexRouteImport } from './routes/dashboard/tutorials/index'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings/index'
import { Route as DashboardServicesIndexRouteImport } from './routes/dashboard/services/index'
import { Route as DashboardPostsIndexRouteImport } from './routes/dashboard/posts/index'
import { Route as DashboardOrgsIndexRouteImport } from './routes/dashboard/orgs/index'
import { Route as DashboardEventsIndexRouteImport } from './routes/dashboard/events/index'
import { Route as DashboardAuditLogsIndexRouteImport } from './routes/dashboard/audit-logs/index'
import { Route as AdminTeamIndexRouteImport } from './routes/admin/team/index'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as AdminServicesIndexRouteImport } from './routes/admin/services/index'
import { Route as AdminRequestsIndexRouteImport } from './routes/admin/requests/index'
import { Route as AdminPostsIndexRouteImport } from './routes/admin/posts/index'
import { Route as AdminConsularRegistryIndexRouteImport } from './routes/admin/consular-registry/index'
import { Route as AdminAppointmentsIndexRouteImport } from './routes/admin/appointments/index'
import { Route as MySpaceRequestsRequestIdRouteImport } from './routes/my-space/requests/$requestId'
import { Route as MySpaceProfileEditRouteImport } from './routes/my-space/profile/edit'
import { Route as MySpaceCompaniesIdRouteImport } from './routes/my-space/companies_.$id'
import { Route as MySpaceAssociationsSlugRouteImport } from './routes/my-space/associations_.$slug'
import { Route as MySpaceAppointmentsNewRouteImport } from './routes/my-space/appointments/new'
import { Route as MySpaceAppointmentsBookRouteImport } from './routes/my-space/appointments/book'
import { Route as DashboardUsersUserIdRouteImport } from './routes/dashboard/users/$userId'
import { Route as DashboardTutorialsNewRouteImport } from './routes/dashboard/tutorials/new'
import { Route as DashboardServicesNewRouteImport } from './routes/dashboard/services/new'
import { Route as DashboardRequestsRequestIdRouteImport } from './routes/dashboard/requests/$requestId'
import { Route as DashboardPostsNewRouteImport } from './routes/dashboard/posts/new'
import { Route as DashboardOrgsNewRouteImport } from './routes/dashboard/orgs/new'
import { Route as DashboardOrgsOrgIdRouteImport } from './routes/dashboard/orgs/$orgId'
import { Route as DashboardEventsNewRouteImport } from './routes/dashboard/events/new'
import { Route as AdminRequestsRequestIdRouteImport } from './routes/admin/requests/$requestId'
import { Route as AdminPostsNewRouteImport } from './routes/admin/posts/new'
import { Route as AdminConsularRegistryPrintQueueRouteImport } from './routes/admin/consular-registry/print-queue'
import { Route as AdminAppointmentsSettingsRouteImport } from './routes/admin/appointments/settings'
import { Route as AdminAppointmentsAgentSchedulesRouteImport } from './routes/admin/appointments/agent-schedules'
import { Route as AdminAppointmentsAppointmentIdRouteImport } from './routes/admin/appointments/$appointmentId'
import { Route as MySpaceServicesSlugNewRouteImport } from './routes/my-space/services/$slug.new'
import { Route as MySpaceRequestsRequestIdAppointmentRouteImport } from './routes/my-space/requests/$requestId_.appointment'
import { Route as DashboardTutorialsTutorialIdEditRouteImport } from './routes/dashboard/tutorials/$tutorialId.edit'
import { Route as DashboardServicesServiceIdFormBuilderRouteImport } from './routes/dashboard/services/$serviceId_.form-builder'
import { Route as DashboardServicesServiceIdEditRouteImport } from './routes/dashboard/services/$serviceId_.edit'
import { Route as DashboardPostsPostIdEditRouteImport } from './routes/dashboard/posts/$postId.edit'
import { Route as DashboardOrgsOrgIdEditRouteImport } from './routes/dashboard/orgs/$orgId_.edit'
import { Route as DashboardEventsEventIdEditRouteImport } from './routes/dashboard/events/$eventId.edit'
import { Route as AdminServicesServiceIdEditRouteImport } from './routes/admin/services/$serviceId.edit'
import { Route as AdminPostsPostIdEditRouteImport } from './routes/admin/posts/$postId.edit'

const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const PostLoginRedirectRoute = PostLoginRedirectRouteImport.update({
  id: '/post-login-redirect',
  path: '/post-login-redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const InformationRoute = InformationRouteImport.update({
  id: '/information',
  path: '/information',
  getParentRoute: () => rootRouteImport,
} as any)
const FormulairesRoute = FormulairesRouteImport.update({
  id: '/formulaires',
  path: '/formulaires',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibiliteRoute = AccessibiliteRouteImport.update({
  id: '/accessibilite',
  path: '/accessibilite',
  getParentRoute: () => rootRouteImport,
} as any)
const MySpaceRouteRoute = MySpaceRouteRouteImport.update({
  id: '/my-space',
  path: '/my-space',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgsIndexRoute = OrgsIndexRouteImport.update({
  id: '/orgs/',
  path: '/orgs/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const MySpaceIndexRoute = MySpaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MySpaceRouteRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AcademyIndexRoute = AcademyIndexRouteImport.update({
  id: '/academy/',
  path: '/academy/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyTokenRoute = VerifyTokenRouteImport.update({
  id: '/verify/$token',
  path: '/verify/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgsSlugRoute = OrgsSlugRouteImport.update({
  id: '/orgs/$slug',
  path: '/orgs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MySpaceVaultRoute = MySpaceVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => MySpaceRouteRoute,
} as any)
const MySpaceSettingsRoute = MySpaceSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MySpaceRouteRoute,
} as any)
const MySpaceRequestsRoute = MySpaceRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => MySpaceRouteRoute,
} as any)
const MySpaceNotificationsRoute = MySpaceNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => MySpaceRouteRoute,
} as any)
const MySpaceIboiteRoute = MySpaceIboiteRouteImport.update({
  id: '/iboite',
  path: '/iboite',
  getParentRoute: () => MySpaceRouteRoute,
} as any)
const MySpaceCvRoute = MySpaceCvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => MySpaceRouteRoute,
} as any)
const MySpaceCompaniesRoute = MySpaceCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => MySpaceRouteRoute,
} as any)
const MySpaceChildrenRoute = MySpaceChildrenRouteImport.update({
  id: '/children',
  path: '/children',
  getParentRoute: () => MySpaceRouteRoute,
} as any)
const MySpaceAssociationsRoute = MySpaceAssociationsRouteImport.update({
  id: '/associations',
  path: '/associations',
  getParentRoute: () => MySpaceRouteRoute,
} as any)
const DashboardAssociationClaimsRoute =
  DashboardAssociationClaimsRouteImport.update({
    id: '/association-claims',
    path: '/association-claims',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const AdminStatisticsRoute = AdminStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AcademySlugRoute = AcademySlugRouteImport.update({
  id: '/academy/$slug',
  path: '/academy/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MySpaceServicesIndexRoute = MySpaceServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => MySpaceRouteRoute,
} as any)
const MySpaceProfileIndexRoute = MySpaceProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => MySpaceRouteRoute,
} as any)
const MySpaceAppointmentsIndexRoute =
  MySpaceAppointmentsIndexRouteImport.update({
    id: '/appointments/',
    path: '/appointments/',
    getParentRoute: () => MySpaceRouteRoute,
  } as any)
const DashboardUsersIndexRoute = DashboardUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTutorialsIndexRoute = DashboardTutorialsIndexRouteImport.update({
  id: '/tutorials/',
  path: '/tutorials/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardServicesIndexRoute = DashboardServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPostsIndexRoute = DashboardPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardOrgsIndexRoute = DashboardOrgsIndexRouteImport.update({
  id: '/orgs/',
  path: '/orgs/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardEventsIndexRoute = DashboardEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAuditLogsIndexRoute = DashboardAuditLogsIndexRouteImport.update({
  id: '/audit-logs/',
  path: '/audit-logs/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AdminTeamIndexRoute = AdminTeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminServicesIndexRoute = AdminServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRequestsIndexRoute = AdminRequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPostsIndexRoute = AdminPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminConsularRegistryIndexRoute =
  AdminConsularRegistryIndexRouteImport.update({
    id: '/consular-registry/',
    path: '/consular-registry/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminAppointmentsIndexRoute = AdminAppointmentsIndexRouteImport.update({
  id: '/appointments/',
  path: '/appointments/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const MySpaceRequestsRequestIdRoute =
  MySpaceRequestsRequestIdRouteImport.update({
    id: '/$requestId',
    path: '/$requestId',
    getParentRoute: () => MySpaceRequestsRoute,
  } as any)
const MySpaceProfileEditRoute = MySpaceProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => MySpaceRouteRoute,
} as any)
const MySpaceCompaniesIdRoute = MySpaceCompaniesIdRouteImport.update({
  id: '/companies_/$id',
  path: '/companies/$id',
  getParentRoute: () => MySpaceRouteRoute,
} as any)
const MySpaceAssociationsSlugRoute = MySpaceAssociationsSlugRouteImport.update({
  id: '/associations_/$slug',
  path: '/associations/$slug',
  getParentRoute: () => MySpaceRouteRoute,
} as any)
const MySpaceAppointmentsNewRoute = MySpaceAppointmentsNewRouteImport.update({
  id: '/appointments/new',
  path: '/appointments/new',
  getParentRoute: () => MySpaceRouteRoute,
} as any)
const MySpaceAppointmentsBookRoute = MySpaceAppointmentsBookRouteImport.update({
  id: '/appointments/book',
  path: '/appointments/book',
  getParentRoute: () => MySpaceRouteRoute,
} as any)
const DashboardUsersUserIdRoute = DashboardUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTutorialsNewRoute = DashboardTutorialsNewRouteImport.update({
  id: '/tutorials/new',
  path: '/tutorials/new',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardServicesNewRoute = DashboardServicesNewRouteImport.update({
  id: '/services/new',
  path: '/services/new',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardRequestsRequestIdRoute =
  DashboardRequestsRequestIdRouteImport.update({
    id: '/requests/$requestId',
    path: '/requests/$requestId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardPostsNewRoute = DashboardPostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardOrgsNewRoute = DashboardOrgsNewRouteImport.update({
  id: '/orgs/new',
  path: '/orgs/new',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardOrgsOrgIdRoute = DashboardOrgsOrgIdRouteImport.update({
  id: '/orgs/$orgId',
  path: '/orgs/$orgId',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardEventsNewRoute = DashboardEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AdminRequestsRequestIdRoute = AdminRequestsRequestIdRouteImport.update({
  id: '/requests/$requestId',
  path: '/requests/$requestId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPostsNewRoute = AdminPostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminConsularRegistryPrintQueueRoute =
  AdminConsularRegistryPrintQueueRouteImport.update({
    id: '/consular-registry/print-queue',
    path: '/consular-registry/print-queue',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminAppointmentsSettingsRoute =
  AdminAppointmentsSettingsRouteImport.update({
    id: '/appointments/settings',
    path: '/appointments/settings',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminAppointmentsAgentSchedulesRoute =
  AdminAppointmentsAgentSchedulesRouteImport.update({
    id: '/appointments/agent-schedules',
    path: '/appointments/agent-schedules',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminAppointmentsAppointmentIdRoute =
  AdminAppointmentsAppointmentIdRouteImport.update({
    id: '/appointments/$appointmentId',
    path: '/appointments/$appointmentId',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const MySpaceServicesSlugNewRoute = MySpaceServicesSlugNewRouteImport.update({
  id: '/services/$slug/new',
  path: '/services/$slug/new',
  getParentRoute: () => MySpaceRouteRoute,
} as any)
const MySpaceRequestsRequestIdAppointmentRoute =
  MySpaceRequestsRequestIdAppointmentRouteImport.update({
    id: '/$requestId_/appointment',
    path: '/$requestId/appointment',
    getParentRoute: () => MySpaceRequestsRoute,
  } as any)
const DashboardTutorialsTutorialIdEditRoute =
  DashboardTutorialsTutorialIdEditRouteImport.update({
    id: '/tutorials/$tutorialId/edit',
    path: '/tutorials/$tutorialId/edit',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardServicesServiceIdFormBuilderRoute =
  DashboardServicesServiceIdFormBuilderRouteImport.update({
    id: '/services/$serviceId_/form-builder',
    path: '/services/$serviceId/form-builder',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardServicesServiceIdEditRoute =
  DashboardServicesServiceIdEditRouteImport.update({
    id: '/services/$serviceId_/edit',
    path: '/services/$serviceId/edit',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardPostsPostIdEditRoute =
  DashboardPostsPostIdEditRouteImport.update({
    id: '/posts/$postId/edit',
    path: '/posts/$postId/edit',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardOrgsOrgIdEditRoute = DashboardOrgsOrgIdEditRouteImport.update({
  id: '/orgs/$orgId_/edit',
  path: '/orgs/$orgId/edit',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardEventsEventIdEditRoute =
  DashboardEventsEventIdEditRouteImport.update({
    id: '/events/$eventId/edit',
    path: '/events/$eventId/edit',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const AdminServicesServiceIdEditRoute =
  AdminServicesServiceIdEditRouteImport.update({
    id: '/services/$serviceId/edit',
    path: '/services/$serviceId/edit',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminPostsPostIdEditRoute = AdminPostsPostIdEditRouteImport.update({
  id: '/posts/$postId/edit',
  path: '/posts/$postId/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/my-space': typeof MySpaceRouteRouteWithChildren
  '/accessibilite': typeof AccessibiliteRoute
  '/community': typeof CommunityRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/faq': typeof FaqRoute
  '/formulaires': typeof FormulairesRoute
  '/information': typeof InformationRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/post-login-redirect': typeof PostLoginRedirectRoute
  '/tarifs': typeof TarifsRoute
  '/academy/$slug': typeof AcademySlugRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/statistics': typeof AdminStatisticsRoute
  '/dashboard/association-claims': typeof DashboardAssociationClaimsRoute
  '/my-space/associations': typeof MySpaceAssociationsRoute
  '/my-space/children': typeof MySpaceChildrenRoute
  '/my-space/companies': typeof MySpaceCompaniesRoute
  '/my-space/cv': typeof MySpaceCvRoute
  '/my-space/iboite': typeof MySpaceIboiteRoute
  '/my-space/notifications': typeof MySpaceNotificationsRoute
  '/my-space/requests': typeof MySpaceRequestsRouteWithChildren
  '/my-space/settings': typeof MySpaceSettingsRoute
  '/my-space/vault': typeof MySpaceVaultRoute
  '/news/$slug': typeof NewsSlugRoute
  '/orgs/$slug': typeof OrgsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/academy': typeof AcademyIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/my-space/': typeof MySpaceIndexRoute
  '/news': typeof NewsIndexRoute
  '/orgs': typeof OrgsIndexRoute
  '/register': typeof RegisterIndexRoute
  '/services': typeof ServicesIndexRoute
  '/admin/appointments/$appointmentId': typeof AdminAppointmentsAppointmentIdRoute
  '/admin/appointments/agent-schedules': typeof AdminAppointmentsAgentSchedulesRoute
  '/admin/appointments/settings': typeof AdminAppointmentsSettingsRoute
  '/admin/consular-registry/print-queue': typeof AdminConsularRegistryPrintQueueRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/admin/requests/$requestId': typeof AdminRequestsRequestIdRoute
  '/dashboard/events/new': typeof DashboardEventsNewRoute
  '/dashboard/orgs/$orgId': typeof DashboardOrgsOrgIdRoute
  '/dashboard/orgs/new': typeof DashboardOrgsNewRoute
  '/dashboard/posts/new': typeof DashboardPostsNewRoute
  '/dashboard/requests/$requestId': typeof DashboardRequestsRequestIdRoute
  '/dashboard/services/new': typeof DashboardServicesNewRoute
  '/dashboard/tutorials/new': typeof DashboardTutorialsNewRoute
  '/dashboard/users/$userId': typeof DashboardUsersUserIdRoute
  '/my-space/appointments/book': typeof MySpaceAppointmentsBookRoute
  '/my-space/appointments/new': typeof MySpaceAppointmentsNewRoute
  '/my-space/associations/$slug': typeof MySpaceAssociationsSlugRoute
  '/my-space/companies/$id': typeof MySpaceCompaniesIdRoute
  '/my-space/profile/edit': typeof MySpaceProfileEditRoute
  '/my-space/requests/$requestId': typeof MySpaceRequestsRequestIdRoute
  '/admin/appointments': typeof AdminAppointmentsIndexRoute
  '/admin/consular-registry': typeof AdminConsularRegistryIndexRoute
  '/admin/posts': typeof AdminPostsIndexRoute
  '/admin/requests': typeof AdminRequestsIndexRoute
  '/admin/services': typeof AdminServicesIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/team': typeof AdminTeamIndexRoute
  '/dashboard/audit-logs': typeof DashboardAuditLogsIndexRoute
  '/dashboard/events': typeof DashboardEventsIndexRoute
  '/dashboard/orgs': typeof DashboardOrgsIndexRoute
  '/dashboard/posts': typeof DashboardPostsIndexRoute
  '/dashboard/services': typeof DashboardServicesIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/dashboard/tutorials': typeof DashboardTutorialsIndexRoute
  '/dashboard/users': typeof DashboardUsersIndexRoute
  '/my-space/appointments': typeof MySpaceAppointmentsIndexRoute
  '/my-space/profile': typeof MySpaceProfileIndexRoute
  '/my-space/services': typeof MySpaceServicesIndexRoute
  '/admin/posts/$postId/edit': typeof AdminPostsPostIdEditRoute
  '/admin/services/$serviceId/edit': typeof AdminServicesServiceIdEditRoute
  '/dashboard/events/$eventId/edit': typeof DashboardEventsEventIdEditRoute
  '/dashboard/orgs/$orgId/edit': typeof DashboardOrgsOrgIdEditRoute
  '/dashboard/posts/$postId/edit': typeof DashboardPostsPostIdEditRoute
  '/dashboard/services/$serviceId/edit': typeof DashboardServicesServiceIdEditRoute
  '/dashboard/services/$serviceId/form-builder': typeof DashboardServicesServiceIdFormBuilderRoute
  '/dashboard/tutorials/$tutorialId/edit': typeof DashboardTutorialsTutorialIdEditRoute
  '/my-space/requests/$requestId/appointment': typeof MySpaceRequestsRequestIdAppointmentRoute
  '/my-space/services/$slug/new': typeof MySpaceServicesSlugNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessibilite': typeof AccessibiliteRoute
  '/community': typeof CommunityRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/faq': typeof FaqRoute
  '/formulaires': typeof FormulairesRoute
  '/information': typeof InformationRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/post-login-redirect': typeof PostLoginRedirectRoute
  '/tarifs': typeof TarifsRoute
  '/academy/$slug': typeof AcademySlugRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/statistics': typeof AdminStatisticsRoute
  '/dashboard/association-claims': typeof DashboardAssociationClaimsRoute
  '/my-space/associations': typeof MySpaceAssociationsRoute
  '/my-space/children': typeof MySpaceChildrenRoute
  '/my-space/companies': typeof MySpaceCompaniesRoute
  '/my-space/cv': typeof MySpaceCvRoute
  '/my-space/iboite': typeof MySpaceIboiteRoute
  '/my-space/notifications': typeof MySpaceNotificationsRoute
  '/my-space/requests': typeof MySpaceRequestsRouteWithChildren
  '/my-space/settings': typeof MySpaceSettingsRoute
  '/my-space/vault': typeof MySpaceVaultRoute
  '/news/$slug': typeof NewsSlugRoute
  '/orgs/$slug': typeof OrgsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/academy': typeof AcademyIndexRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/my-space': typeof MySpaceIndexRoute
  '/news': typeof NewsIndexRoute
  '/orgs': typeof OrgsIndexRoute
  '/register': typeof RegisterIndexRoute
  '/services': typeof ServicesIndexRoute
  '/admin/appointments/$appointmentId': typeof AdminAppointmentsAppointmentIdRoute
  '/admin/appointments/agent-schedules': typeof AdminAppointmentsAgentSchedulesRoute
  '/admin/appointments/settings': typeof AdminAppointmentsSettingsRoute
  '/admin/consular-registry/print-queue': typeof AdminConsularRegistryPrintQueueRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/admin/requests/$requestId': typeof AdminRequestsRequestIdRoute
  '/dashboard/events/new': typeof DashboardEventsNewRoute
  '/dashboard/orgs/$orgId': typeof DashboardOrgsOrgIdRoute
  '/dashboard/orgs/new': typeof DashboardOrgsNewRoute
  '/dashboard/posts/new': typeof DashboardPostsNewRoute
  '/dashboard/requests/$requestId': typeof DashboardRequestsRequestIdRoute
  '/dashboard/services/new': typeof DashboardServicesNewRoute
  '/dashboard/tutorials/new': typeof DashboardTutorialsNewRoute
  '/dashboard/users/$userId': typeof DashboardUsersUserIdRoute
  '/my-space/appointments/book': typeof MySpaceAppointmentsBookRoute
  '/my-space/appointments/new': typeof MySpaceAppointmentsNewRoute
  '/my-space/associations/$slug': typeof MySpaceAssociationsSlugRoute
  '/my-space/companies/$id': typeof MySpaceCompaniesIdRoute
  '/my-space/profile/edit': typeof MySpaceProfileEditRoute
  '/my-space/requests/$requestId': typeof MySpaceRequestsRequestIdRoute
  '/admin/appointments': typeof AdminAppointmentsIndexRoute
  '/admin/consular-registry': typeof AdminConsularRegistryIndexRoute
  '/admin/posts': typeof AdminPostsIndexRoute
  '/admin/requests': typeof AdminRequestsIndexRoute
  '/admin/services': typeof AdminServicesIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/team': typeof AdminTeamIndexRoute
  '/dashboard/audit-logs': typeof DashboardAuditLogsIndexRoute
  '/dashboard/events': typeof DashboardEventsIndexRoute
  '/dashboard/orgs': typeof DashboardOrgsIndexRoute
  '/dashboard/posts': typeof DashboardPostsIndexRoute
  '/dashboard/services': typeof DashboardServicesIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/dashboard/tutorials': typeof DashboardTutorialsIndexRoute
  '/dashboard/users': typeof DashboardUsersIndexRoute
  '/my-space/appointments': typeof MySpaceAppointmentsIndexRoute
  '/my-space/profile': typeof MySpaceProfileIndexRoute
  '/my-space/services': typeof MySpaceServicesIndexRoute
  '/admin/posts/$postId/edit': typeof AdminPostsPostIdEditRoute
  '/admin/services/$serviceId/edit': typeof AdminServicesServiceIdEditRoute
  '/dashboard/events/$eventId/edit': typeof DashboardEventsEventIdEditRoute
  '/dashboard/orgs/$orgId/edit': typeof DashboardOrgsOrgIdEditRoute
  '/dashboard/posts/$postId/edit': typeof DashboardPostsPostIdEditRoute
  '/dashboard/services/$serviceId/edit': typeof DashboardServicesServiceIdEditRoute
  '/dashboard/services/$serviceId/form-builder': typeof DashboardServicesServiceIdFormBuilderRoute
  '/dashboard/tutorials/$tutorialId/edit': typeof DashboardTutorialsTutorialIdEditRoute
  '/my-space/requests/$requestId/appointment': typeof MySpaceRequestsRequestIdAppointmentRoute
  '/my-space/services/$slug/new': typeof MySpaceServicesSlugNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/my-space': typeof MySpaceRouteRouteWithChildren
  '/accessibilite': typeof AccessibiliteRoute
  '/community': typeof CommunityRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/faq': typeof FaqRoute
  '/formulaires': typeof FormulairesRoute
  '/information': typeof InformationRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/post-login-redirect': typeof PostLoginRedirectRoute
  '/tarifs': typeof TarifsRoute
  '/academy/$slug': typeof AcademySlugRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/statistics': typeof AdminStatisticsRoute
  '/dashboard/association-claims': typeof DashboardAssociationClaimsRoute
  '/my-space/associations': typeof MySpaceAssociationsRoute
  '/my-space/children': typeof MySpaceChildrenRoute
  '/my-space/companies': typeof MySpaceCompaniesRoute
  '/my-space/cv': typeof MySpaceCvRoute
  '/my-space/iboite': typeof MySpaceIboiteRoute
  '/my-space/notifications': typeof MySpaceNotificationsRoute
  '/my-space/requests': typeof MySpaceRequestsRouteWithChildren
  '/my-space/settings': typeof MySpaceSettingsRoute
  '/my-space/vault': typeof MySpaceVaultRoute
  '/news/$slug': typeof NewsSlugRoute
  '/orgs/$slug': typeof OrgsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/academy/': typeof AcademyIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/my-space/': typeof MySpaceIndexRoute
  '/news/': typeof NewsIndexRoute
  '/orgs/': typeof OrgsIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/admin/appointments/$appointmentId': typeof AdminAppointmentsAppointmentIdRoute
  '/admin/appointments/agent-schedules': typeof AdminAppointmentsAgentSchedulesRoute
  '/admin/appointments/settings': typeof AdminAppointmentsSettingsRoute
  '/admin/consular-registry/print-queue': typeof AdminConsularRegistryPrintQueueRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/admin/requests/$requestId': typeof AdminRequestsRequestIdRoute
  '/dashboard/events/new': typeof DashboardEventsNewRoute
  '/dashboard/orgs/$orgId': typeof DashboardOrgsOrgIdRoute
  '/dashboard/orgs/new': typeof DashboardOrgsNewRoute
  '/dashboard/posts/new': typeof DashboardPostsNewRoute
  '/dashboard/requests/$requestId': typeof DashboardRequestsRequestIdRoute
  '/dashboard/services/new': typeof DashboardServicesNewRoute
  '/dashboard/tutorials/new': typeof DashboardTutorialsNewRoute
  '/dashboard/users/$userId': typeof DashboardUsersUserIdRoute
  '/my-space/appointments/book': typeof MySpaceAppointmentsBookRoute
  '/my-space/appointments/new': typeof MySpaceAppointmentsNewRoute
  '/my-space/associations_/$slug': typeof MySpaceAssociationsSlugRoute
  '/my-space/companies_/$id': typeof MySpaceCompaniesIdRoute
  '/my-space/profile/edit': typeof MySpaceProfileEditRoute
  '/my-space/requests/$requestId': typeof MySpaceRequestsRequestIdRoute
  '/admin/appointments/': typeof AdminAppointmentsIndexRoute
  '/admin/consular-registry/': typeof AdminConsularRegistryIndexRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/admin/requests/': typeof AdminRequestsIndexRoute
  '/admin/services/': typeof AdminServicesIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/team/': typeof AdminTeamIndexRoute
  '/dashboard/audit-logs/': typeof DashboardAuditLogsIndexRoute
  '/dashboard/events/': typeof DashboardEventsIndexRoute
  '/dashboard/orgs/': typeof DashboardOrgsIndexRoute
  '/dashboard/posts/': typeof DashboardPostsIndexRoute
  '/dashboard/services/': typeof DashboardServicesIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/tutorials/': typeof DashboardTutorialsIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
  '/my-space/appointments/': typeof MySpaceAppointmentsIndexRoute
  '/my-space/profile/': typeof MySpaceProfileIndexRoute
  '/my-space/services/': typeof MySpaceServicesIndexRoute
  '/admin/posts/$postId/edit': typeof AdminPostsPostIdEditRoute
  '/admin/services/$serviceId/edit': typeof AdminServicesServiceIdEditRoute
  '/dashboard/events/$eventId/edit': typeof DashboardEventsEventIdEditRoute
  '/dashboard/orgs/$orgId_/edit': typeof DashboardOrgsOrgIdEditRoute
  '/dashboard/posts/$postId/edit': typeof DashboardPostsPostIdEditRoute
  '/dashboard/services/$serviceId_/edit': typeof DashboardServicesServiceIdEditRoute
  '/dashboard/services/$serviceId_/form-builder': typeof DashboardServicesServiceIdFormBuilderRoute
  '/dashboard/tutorials/$tutorialId/edit': typeof DashboardTutorialsTutorialIdEditRoute
  '/my-space/requests/$requestId_/appointment': typeof MySpaceRequestsRequestIdAppointmentRoute
  '/my-space/services/$slug/new': typeof MySpaceServicesSlugNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/my-space'
    | '/accessibilite'
    | '/community'
    | '/confidentialite'
    | '/faq'
    | '/formulaires'
    | '/information'
    | '/mentions-legales'
    | '/post-login-redirect'
    | '/tarifs'
    | '/academy/$slug'
    | '/admin/payments'
    | '/admin/statistics'
    | '/dashboard/association-claims'
    | '/my-space/associations'
    | '/my-space/children'
    | '/my-space/companies'
    | '/my-space/cv'
    | '/my-space/iboite'
    | '/my-space/notifications'
    | '/my-space/requests'
    | '/my-space/settings'
    | '/my-space/vault'
    | '/news/$slug'
    | '/orgs/$slug'
    | '/services/$slug'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/verify/$token'
    | '/academy'
    | '/admin/'
    | '/dashboard/'
    | '/my-space/'
    | '/news'
    | '/orgs'
    | '/register'
    | '/services'
    | '/admin/appointments/$appointmentId'
    | '/admin/appointments/agent-schedules'
    | '/admin/appointments/settings'
    | '/admin/consular-registry/print-queue'
    | '/admin/posts/new'
    | '/admin/requests/$requestId'
    | '/dashboard/events/new'
    | '/dashboard/orgs/$orgId'
    | '/dashboard/orgs/new'
    | '/dashboard/posts/new'
    | '/dashboard/requests/$requestId'
    | '/dashboard/services/new'
    | '/dashboard/tutorials/new'
    | '/dashboard/users/$userId'
    | '/my-space/appointments/book'
    | '/my-space/appointments/new'
    | '/my-space/associations/$slug'
    | '/my-space/companies/$id'
    | '/my-space/profile/edit'
    | '/my-space/requests/$requestId'
    | '/admin/appointments'
    | '/admin/consular-registry'
    | '/admin/posts'
    | '/admin/requests'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/team'
    | '/dashboard/audit-logs'
    | '/dashboard/events'
    | '/dashboard/orgs'
    | '/dashboard/posts'
    | '/dashboard/services'
    | '/dashboard/settings'
    | '/dashboard/tutorials'
    | '/dashboard/users'
    | '/my-space/appointments'
    | '/my-space/profile'
    | '/my-space/services'
    | '/admin/posts/$postId/edit'
    | '/admin/services/$serviceId/edit'
    | '/dashboard/events/$eventId/edit'
    | '/dashboard/orgs/$orgId/edit'
    | '/dashboard/posts/$postId/edit'
    | '/dashboard/services/$serviceId/edit'
    | '/dashboard/services/$serviceId/form-builder'
    | '/dashboard/tutorials/$tutorialId/edit'
    | '/my-space/requests/$requestId/appointment'
    | '/my-space/services/$slug/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessibilite'
    | '/community'
    | '/confidentialite'
    | '/faq'
    | '/formulaires'
    | '/information'
    | '/mentions-legales'
    | '/post-login-redirect'
    | '/tarifs'
    | '/academy/$slug'
    | '/admin/payments'
    | '/admin/statistics'
    | '/dashboard/association-claims'
    | '/my-space/associations'
    | '/my-space/children'
    | '/my-space/companies'
    | '/my-space/cv'
    | '/my-space/iboite'
    | '/my-space/notifications'
    | '/my-space/requests'
    | '/my-space/settings'
    | '/my-space/vault'
    | '/news/$slug'
    | '/orgs/$slug'
    | '/services/$slug'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/verify/$token'
    | '/academy'
    | '/admin'
    | '/dashboard'
    | '/my-space'
    | '/news'
    | '/orgs'
    | '/register'
    | '/services'
    | '/admin/appointments/$appointmentId'
    | '/admin/appointments/agent-schedules'
    | '/admin/appointments/settings'
    | '/admin/consular-registry/print-queue'
    | '/admin/posts/new'
    | '/admin/requests/$requestId'
    | '/dashboard/events/new'
    | '/dashboard/orgs/$orgId'
    | '/dashboard/orgs/new'
    | '/dashboard/posts/new'
    | '/dashboard/requests/$requestId'
    | '/dashboard/services/new'
    | '/dashboard/tutorials/new'
    | '/dashboard/users/$userId'
    | '/my-space/appointments/book'
    | '/my-space/appointments/new'
    | '/my-space/associations/$slug'
    | '/my-space/companies/$id'
    | '/my-space/profile/edit'
    | '/my-space/requests/$requestId'
    | '/admin/appointments'
    | '/admin/consular-registry'
    | '/admin/posts'
    | '/admin/requests'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/team'
    | '/dashboard/audit-logs'
    | '/dashboard/events'
    | '/dashboard/orgs'
    | '/dashboard/posts'
    | '/dashboard/services'
    | '/dashboard/settings'
    | '/dashboard/tutorials'
    | '/dashboard/users'
    | '/my-space/appointments'
    | '/my-space/profile'
    | '/my-space/services'
    | '/admin/posts/$postId/edit'
    | '/admin/services/$serviceId/edit'
    | '/dashboard/events/$eventId/edit'
    | '/dashboard/orgs/$orgId/edit'
    | '/dashboard/posts/$postId/edit'
    | '/dashboard/services/$serviceId/edit'
    | '/dashboard/services/$serviceId/form-builder'
    | '/dashboard/tutorials/$tutorialId/edit'
    | '/my-space/requests/$requestId/appointment'
    | '/my-space/services/$slug/new'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/my-space'
    | '/accessibilite'
    | '/community'
    | '/confidentialite'
    | '/faq'
    | '/formulaires'
    | '/information'
    | '/mentions-legales'
    | '/post-login-redirect'
    | '/tarifs'
    | '/academy/$slug'
    | '/admin/payments'
    | '/admin/statistics'
    | '/dashboard/association-claims'
    | '/my-space/associations'
    | '/my-space/children'
    | '/my-space/companies'
    | '/my-space/cv'
    | '/my-space/iboite'
    | '/my-space/notifications'
    | '/my-space/requests'
    | '/my-space/settings'
    | '/my-space/vault'
    | '/news/$slug'
    | '/orgs/$slug'
    | '/services/$slug'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/verify/$token'
    | '/academy/'
    | '/admin/'
    | '/dashboard/'
    | '/my-space/'
    | '/news/'
    | '/orgs/'
    | '/register/'
    | '/services/'
    | '/admin/appointments/$appointmentId'
    | '/admin/appointments/agent-schedules'
    | '/admin/appointments/settings'
    | '/admin/consular-registry/print-queue'
    | '/admin/posts/new'
    | '/admin/requests/$requestId'
    | '/dashboard/events/new'
    | '/dashboard/orgs/$orgId'
    | '/dashboard/orgs/new'
    | '/dashboard/posts/new'
    | '/dashboard/requests/$requestId'
    | '/dashboard/services/new'
    | '/dashboard/tutorials/new'
    | '/dashboard/users/$userId'
    | '/my-space/appointments/book'
    | '/my-space/appointments/new'
    | '/my-space/associations_/$slug'
    | '/my-space/companies_/$id'
    | '/my-space/profile/edit'
    | '/my-space/requests/$requestId'
    | '/admin/appointments/'
    | '/admin/consular-registry/'
    | '/admin/posts/'
    | '/admin/requests/'
    | '/admin/services/'
    | '/admin/settings/'
    | '/admin/team/'
    | '/dashboard/audit-logs/'
    | '/dashboard/events/'
    | '/dashboard/orgs/'
    | '/dashboard/posts/'
    | '/dashboard/services/'
    | '/dashboard/settings/'
    | '/dashboard/tutorials/'
    | '/dashboard/users/'
    | '/my-space/appointments/'
    | '/my-space/profile/'
    | '/my-space/services/'
    | '/admin/posts/$postId/edit'
    | '/admin/services/$serviceId/edit'
    | '/dashboard/events/$eventId/edit'
    | '/dashboard/orgs/$orgId_/edit'
    | '/dashboard/posts/$postId/edit'
    | '/dashboard/services/$serviceId_/edit'
    | '/dashboard/services/$serviceId_/form-builder'
    | '/dashboard/tutorials/$tutorialId/edit'
    | '/my-space/requests/$requestId_/appointment'
    | '/my-space/services/$slug/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  MySpaceRouteRoute: typeof MySpaceRouteRouteWithChildren
  AccessibiliteRoute: typeof AccessibiliteRoute
  CommunityRoute: typeof CommunityRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  FaqRoute: typeof FaqRoute
  FormulairesRoute: typeof FormulairesRoute
  InformationRoute: typeof InformationRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  PostLoginRedirectRoute: typeof PostLoginRedirectRoute
  TarifsRoute: typeof TarifsRoute
  AcademySlugRoute: typeof AcademySlugRoute
  NewsSlugRoute: typeof NewsSlugRoute
  OrgsSlugRoute: typeof OrgsSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
  VerifyTokenRoute: typeof VerifyTokenRoute
  AcademyIndexRoute: typeof AcademyIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
  OrgsIndexRoute: typeof OrgsIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-login-redirect': {
      id: '/post-login-redirect'
      path: '/post-login-redirect'
      fullPath: '/post-login-redirect'
      preLoaderRoute: typeof PostLoginRedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/information': {
      id: '/information'
      path: '/information'
      fullPath: '/information'
      preLoaderRoute: typeof InformationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formulaires': {
      id: '/formulaires'
      path: '/formulaires'
      fullPath: '/formulaires'
      preLoaderRoute: typeof FormulairesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibilite': {
      id: '/accessibilite'
      path: '/accessibilite'
      fullPath: '/accessibilite'
      preLoaderRoute: typeof AccessibiliteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-space': {
      id: '/my-space'
      path: '/my-space'
      fullPath: '/my-space'
      preLoaderRoute: typeof MySpaceRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs/': {
      id: '/orgs/'
      path: '/orgs'
      fullPath: '/orgs'
      preLoaderRoute: typeof OrgsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-space/': {
      id: '/my-space/'
      path: '/'
      fullPath: '/my-space/'
      preLoaderRoute: typeof MySpaceIndexRouteImport
      parentRoute: typeof MySpaceRouteRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/academy/': {
      id: '/academy/'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$token': {
      id: '/verify/$token'
      path: '/verify/$token'
      fullPath: '/verify/$token'
      preLoaderRoute: typeof VerifyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs/$slug': {
      id: '/orgs/$slug'
      path: '/orgs/$slug'
      fullPath: '/orgs/$slug'
      preLoaderRoute: typeof OrgsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-space/vault': {
      id: '/my-space/vault'
      path: '/vault'
      fullPath: '/my-space/vault'
      preLoaderRoute: typeof MySpaceVaultRouteImport
      parentRoute: typeof MySpaceRouteRoute
    }
    '/my-space/settings': {
      id: '/my-space/settings'
      path: '/settings'
      fullPath: '/my-space/settings'
      preLoaderRoute: typeof MySpaceSettingsRouteImport
      parentRoute: typeof MySpaceRouteRoute
    }
    '/my-space/requests': {
      id: '/my-space/requests'
      path: '/requests'
      fullPath: '/my-space/requests'
      preLoaderRoute: typeof MySpaceRequestsRouteImport
      parentRoute: typeof MySpaceRouteRoute
    }
    '/my-space/notifications': {
      id: '/my-space/notifications'
      path: '/notifications'
      fullPath: '/my-space/notifications'
      preLoaderRoute: typeof MySpaceNotificationsRouteImport
      parentRoute: typeof MySpaceRouteRoute
    }
    '/my-space/iboite': {
      id: '/my-space/iboite'
      path: '/iboite'
      fullPath: '/my-space/iboite'
      preLoaderRoute: typeof MySpaceIboiteRouteImport
      parentRoute: typeof MySpaceRouteRoute
    }
    '/my-space/cv': {
      id: '/my-space/cv'
      path: '/cv'
      fullPath: '/my-space/cv'
      preLoaderRoute: typeof MySpaceCvRouteImport
      parentRoute: typeof MySpaceRouteRoute
    }
    '/my-space/companies': {
      id: '/my-space/companies'
      path: '/companies'
      fullPath: '/my-space/companies'
      preLoaderRoute: typeof MySpaceCompaniesRouteImport
      parentRoute: typeof MySpaceRouteRoute
    }
    '/my-space/children': {
      id: '/my-space/children'
      path: '/children'
      fullPath: '/my-space/children'
      preLoaderRoute: typeof MySpaceChildrenRouteImport
      parentRoute: typeof MySpaceRouteRoute
    }
    '/my-space/associations': {
      id: '/my-space/associations'
      path: '/associations'
      fullPath: '/my-space/associations'
      preLoaderRoute: typeof MySpaceAssociationsRouteImport
      parentRoute: typeof MySpaceRouteRoute
    }
    '/dashboard/association-claims': {
      id: '/dashboard/association-claims'
      path: '/association-claims'
      fullPath: '/dashboard/association-claims'
      preLoaderRoute: typeof DashboardAssociationClaimsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/admin/statistics': {
      id: '/admin/statistics'
      path: '/statistics'
      fullPath: '/admin/statistics'
      preLoaderRoute: typeof AdminStatisticsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/academy/$slug': {
      id: '/academy/$slug'
      path: '/academy/$slug'
      fullPath: '/academy/$slug'
      preLoaderRoute: typeof AcademySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-space/services/': {
      id: '/my-space/services/'
      path: '/services'
      fullPath: '/my-space/services'
      preLoaderRoute: typeof MySpaceServicesIndexRouteImport
      parentRoute: typeof MySpaceRouteRoute
    }
    '/my-space/profile/': {
      id: '/my-space/profile/'
      path: '/profile'
      fullPath: '/my-space/profile'
      preLoaderRoute: typeof MySpaceProfileIndexRouteImport
      parentRoute: typeof MySpaceRouteRoute
    }
    '/my-space/appointments/': {
      id: '/my-space/appointments/'
      path: '/appointments'
      fullPath: '/my-space/appointments'
      preLoaderRoute: typeof MySpaceAppointmentsIndexRouteImport
      parentRoute: typeof MySpaceRouteRoute
    }
    '/dashboard/users/': {
      id: '/dashboard/users/'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/tutorials/': {
      id: '/dashboard/tutorials/'
      path: '/tutorials'
      fullPath: '/dashboard/tutorials'
      preLoaderRoute: typeof DashboardTutorialsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/services/': {
      id: '/dashboard/services/'
      path: '/services'
      fullPath: '/dashboard/services'
      preLoaderRoute: typeof DashboardServicesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/posts/': {
      id: '/dashboard/posts/'
      path: '/posts'
      fullPath: '/dashboard/posts'
      preLoaderRoute: typeof DashboardPostsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/orgs/': {
      id: '/dashboard/orgs/'
      path: '/orgs'
      fullPath: '/dashboard/orgs'
      preLoaderRoute: typeof DashboardOrgsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/events/': {
      id: '/dashboard/events/'
      path: '/events'
      fullPath: '/dashboard/events'
      preLoaderRoute: typeof DashboardEventsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/audit-logs/': {
      id: '/dashboard/audit-logs/'
      path: '/audit-logs'
      fullPath: '/dashboard/audit-logs'
      preLoaderRoute: typeof DashboardAuditLogsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/admin/team/': {
      id: '/admin/team/'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/services/': {
      id: '/admin/services/'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/requests/': {
      id: '/admin/requests/'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/posts/': {
      id: '/admin/posts/'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/consular-registry/': {
      id: '/admin/consular-registry/'
      path: '/consular-registry'
      fullPath: '/admin/consular-registry'
      preLoaderRoute: typeof AdminConsularRegistryIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/appointments/': {
      id: '/admin/appointments/'
      path: '/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AdminAppointmentsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/my-space/requests/$requestId': {
      id: '/my-space/requests/$requestId'
      path: '/$requestId'
      fullPath: '/my-space/requests/$requestId'
      preLoaderRoute: typeof MySpaceRequestsRequestIdRouteImport
      parentRoute: typeof MySpaceRequestsRoute
    }
    '/my-space/profile/edit': {
      id: '/my-space/profile/edit'
      path: '/profile/edit'
      fullPath: '/my-space/profile/edit'
      preLoaderRoute: typeof MySpaceProfileEditRouteImport
      parentRoute: typeof MySpaceRouteRoute
    }
    '/my-space/companies_/$id': {
      id: '/my-space/companies_/$id'
      path: '/companies/$id'
      fullPath: '/my-space/companies/$id'
      preLoaderRoute: typeof MySpaceCompaniesIdRouteImport
      parentRoute: typeof MySpaceRouteRoute
    }
    '/my-space/associations_/$slug': {
      id: '/my-space/associations_/$slug'
      path: '/associations/$slug'
      fullPath: '/my-space/associations/$slug'
      preLoaderRoute: typeof MySpaceAssociationsSlugRouteImport
      parentRoute: typeof MySpaceRouteRoute
    }
    '/my-space/appointments/new': {
      id: '/my-space/appointments/new'
      path: '/appointments/new'
      fullPath: '/my-space/appointments/new'
      preLoaderRoute: typeof MySpaceAppointmentsNewRouteImport
      parentRoute: typeof MySpaceRouteRoute
    }
    '/my-space/appointments/book': {
      id: '/my-space/appointments/book'
      path: '/appointments/book'
      fullPath: '/my-space/appointments/book'
      preLoaderRoute: typeof MySpaceAppointmentsBookRouteImport
      parentRoute: typeof MySpaceRouteRoute
    }
    '/dashboard/users/$userId': {
      id: '/dashboard/users/$userId'
      path: '/users/$userId'
      fullPath: '/dashboard/users/$userId'
      preLoaderRoute: typeof DashboardUsersUserIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/tutorials/new': {
      id: '/dashboard/tutorials/new'
      path: '/tutorials/new'
      fullPath: '/dashboard/tutorials/new'
      preLoaderRoute: typeof DashboardTutorialsNewRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/services/new': {
      id: '/dashboard/services/new'
      path: '/services/new'
      fullPath: '/dashboard/services/new'
      preLoaderRoute: typeof DashboardServicesNewRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/requests/$requestId': {
      id: '/dashboard/requests/$requestId'
      path: '/requests/$requestId'
      fullPath: '/dashboard/requests/$requestId'
      preLoaderRoute: typeof DashboardRequestsRequestIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/posts/new': {
      id: '/dashboard/posts/new'
      path: '/posts/new'
      fullPath: '/dashboard/posts/new'
      preLoaderRoute: typeof DashboardPostsNewRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/orgs/new': {
      id: '/dashboard/orgs/new'
      path: '/orgs/new'
      fullPath: '/dashboard/orgs/new'
      preLoaderRoute: typeof DashboardOrgsNewRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/orgs/$orgId': {
      id: '/dashboard/orgs/$orgId'
      path: '/orgs/$orgId'
      fullPath: '/dashboard/orgs/$orgId'
      preLoaderRoute: typeof DashboardOrgsOrgIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/events/new': {
      id: '/dashboard/events/new'
      path: '/events/new'
      fullPath: '/dashboard/events/new'
      preLoaderRoute: typeof DashboardEventsNewRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/admin/requests/$requestId': {
      id: '/admin/requests/$requestId'
      path: '/requests/$requestId'
      fullPath: '/admin/requests/$requestId'
      preLoaderRoute: typeof AdminRequestsRequestIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/posts/new': {
      id: '/admin/posts/new'
      path: '/posts/new'
      fullPath: '/admin/posts/new'
      preLoaderRoute: typeof AdminPostsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/consular-registry/print-queue': {
      id: '/admin/consular-registry/print-queue'
      path: '/consular-registry/print-queue'
      fullPath: '/admin/consular-registry/print-queue'
      preLoaderRoute: typeof AdminConsularRegistryPrintQueueRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/appointments/settings': {
      id: '/admin/appointments/settings'
      path: '/appointments/settings'
      fullPath: '/admin/appointments/settings'
      preLoaderRoute: typeof AdminAppointmentsSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/appointments/agent-schedules': {
      id: '/admin/appointments/agent-schedules'
      path: '/appointments/agent-schedules'
      fullPath: '/admin/appointments/agent-schedules'
      preLoaderRoute: typeof AdminAppointmentsAgentSchedulesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/appointments/$appointmentId': {
      id: '/admin/appointments/$appointmentId'
      path: '/appointments/$appointmentId'
      fullPath: '/admin/appointments/$appointmentId'
      preLoaderRoute: typeof AdminAppointmentsAppointmentIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/my-space/services/$slug/new': {
      id: '/my-space/services/$slug/new'
      path: '/services/$slug/new'
      fullPath: '/my-space/services/$slug/new'
      preLoaderRoute: typeof MySpaceServicesSlugNewRouteImport
      parentRoute: typeof MySpaceRouteRoute
    }
    '/my-space/requests/$requestId_/appointment': {
      id: '/my-space/requests/$requestId_/appointment'
      path: '/$requestId/appointment'
      fullPath: '/my-space/requests/$requestId/appointment'
      preLoaderRoute: typeof MySpaceRequestsRequestIdAppointmentRouteImport
      parentRoute: typeof MySpaceRequestsRoute
    }
    '/dashboard/tutorials/$tutorialId/edit': {
      id: '/dashboard/tutorials/$tutorialId/edit'
      path: '/tutorials/$tutorialId/edit'
      fullPath: '/dashboard/tutorials/$tutorialId/edit'
      preLoaderRoute: typeof DashboardTutorialsTutorialIdEditRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/services/$serviceId_/form-builder': {
      id: '/dashboard/services/$serviceId_/form-builder'
      path: '/services/$serviceId/form-builder'
      fullPath: '/dashboard/services/$serviceId/form-builder'
      preLoaderRoute: typeof DashboardServicesServiceIdFormBuilderRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/services/$serviceId_/edit': {
      id: '/dashboard/services/$serviceId_/edit'
      path: '/services/$serviceId/edit'
      fullPath: '/dashboard/services/$serviceId/edit'
      preLoaderRoute: typeof DashboardServicesServiceIdEditRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/posts/$postId/edit': {
      id: '/dashboard/posts/$postId/edit'
      path: '/posts/$postId/edit'
      fullPath: '/dashboard/posts/$postId/edit'
      preLoaderRoute: typeof DashboardPostsPostIdEditRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/orgs/$orgId_/edit': {
      id: '/dashboard/orgs/$orgId_/edit'
      path: '/orgs/$orgId/edit'
      fullPath: '/dashboard/orgs/$orgId/edit'
      preLoaderRoute: typeof DashboardOrgsOrgIdEditRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/events/$eventId/edit': {
      id: '/dashboard/events/$eventId/edit'
      path: '/events/$eventId/edit'
      fullPath: '/dashboard/events/$eventId/edit'
      preLoaderRoute: typeof DashboardEventsEventIdEditRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/admin/services/$serviceId/edit': {
      id: '/admin/services/$serviceId/edit'
      path: '/services/$serviceId/edit'
      fullPath: '/admin/services/$serviceId/edit'
      preLoaderRoute: typeof AdminServicesServiceIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/posts/$postId/edit': {
      id: '/admin/posts/$postId/edit'
      path: '/posts/$postId/edit'
      fullPath: '/admin/posts/$postId/edit'
      preLoaderRoute: typeof AdminPostsPostIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminStatisticsRoute: typeof AdminStatisticsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAppointmentsAppointmentIdRoute: typeof AdminAppointmentsAppointmentIdRoute
  AdminAppointmentsAgentSchedulesRoute: typeof AdminAppointmentsAgentSchedulesRoute
  AdminAppointmentsSettingsRoute: typeof AdminAppointmentsSettingsRoute
  AdminConsularRegistryPrintQueueRoute: typeof AdminConsularRegistryPrintQueueRoute
  AdminPostsNewRoute: typeof AdminPostsNewRoute
  AdminRequestsRequestIdRoute: typeof AdminRequestsRequestIdRoute
  AdminAppointmentsIndexRoute: typeof AdminAppointmentsIndexRoute
  AdminConsularRegistryIndexRoute: typeof AdminConsularRegistryIndexRoute
  AdminPostsIndexRoute: typeof AdminPostsIndexRoute
  AdminRequestsIndexRoute: typeof AdminRequestsIndexRoute
  AdminServicesIndexRoute: typeof AdminServicesIndexRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
  AdminTeamIndexRoute: typeof AdminTeamIndexRoute
  AdminPostsPostIdEditRoute: typeof AdminPostsPostIdEditRoute
  AdminServicesServiceIdEditRoute: typeof AdminServicesServiceIdEditRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminStatisticsRoute: AdminStatisticsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAppointmentsAppointmentIdRoute: AdminAppointmentsAppointmentIdRoute,
  AdminAppointmentsAgentSchedulesRoute: AdminAppointmentsAgentSchedulesRoute,
  AdminAppointmentsSettingsRoute: AdminAppointmentsSettingsRoute,
  AdminConsularRegistryPrintQueueRoute: AdminConsularRegistryPrintQueueRoute,
  AdminPostsNewRoute: AdminPostsNewRoute,
  AdminRequestsRequestIdRoute: AdminRequestsRequestIdRoute,
  AdminAppointmentsIndexRoute: AdminAppointmentsIndexRoute,
  AdminConsularRegistryIndexRoute: AdminConsularRegistryIndexRoute,
  AdminPostsIndexRoute: AdminPostsIndexRoute,
  AdminRequestsIndexRoute: AdminRequestsIndexRoute,
  AdminServicesIndexRoute: AdminServicesIndexRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
  AdminTeamIndexRoute: AdminTeamIndexRoute,
  AdminPostsPostIdEditRoute: AdminPostsPostIdEditRoute,
  AdminServicesServiceIdEditRoute: AdminServicesServiceIdEditRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardAssociationClaimsRoute: typeof DashboardAssociationClaimsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardEventsNewRoute: typeof DashboardEventsNewRoute
  DashboardOrgsOrgIdRoute: typeof DashboardOrgsOrgIdRoute
  DashboardOrgsNewRoute: typeof DashboardOrgsNewRoute
  DashboardPostsNewRoute: typeof DashboardPostsNewRoute
  DashboardRequestsRequestIdRoute: typeof DashboardRequestsRequestIdRoute
  DashboardServicesNewRoute: typeof DashboardServicesNewRoute
  DashboardTutorialsNewRoute: typeof DashboardTutorialsNewRoute
  DashboardUsersUserIdRoute: typeof DashboardUsersUserIdRoute
  DashboardAuditLogsIndexRoute: typeof DashboardAuditLogsIndexRoute
  DashboardEventsIndexRoute: typeof DashboardEventsIndexRoute
  DashboardOrgsIndexRoute: typeof DashboardOrgsIndexRoute
  DashboardPostsIndexRoute: typeof DashboardPostsIndexRoute
  DashboardServicesIndexRoute: typeof DashboardServicesIndexRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
  DashboardTutorialsIndexRoute: typeof DashboardTutorialsIndexRoute
  DashboardUsersIndexRoute: typeof DashboardUsersIndexRoute
  DashboardEventsEventIdEditRoute: typeof DashboardEventsEventIdEditRoute
  DashboardOrgsOrgIdEditRoute: typeof DashboardOrgsOrgIdEditRoute
  DashboardPostsPostIdEditRoute: typeof DashboardPostsPostIdEditRoute
  DashboardServicesServiceIdEditRoute: typeof DashboardServicesServiceIdEditRoute
  DashboardServicesServiceIdFormBuilderRoute: typeof DashboardServicesServiceIdFormBuilderRoute
  DashboardTutorialsTutorialIdEditRoute: typeof DashboardTutorialsTutorialIdEditRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAssociationClaimsRoute: DashboardAssociationClaimsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardEventsNewRoute: DashboardEventsNewRoute,
  DashboardOrgsOrgIdRoute: DashboardOrgsOrgIdRoute,
  DashboardOrgsNewRoute: DashboardOrgsNewRoute,
  DashboardPostsNewRoute: DashboardPostsNewRoute,
  DashboardRequestsRequestIdRoute: DashboardRequestsRequestIdRoute,
  DashboardServicesNewRoute: DashboardServicesNewRoute,
  DashboardTutorialsNewRoute: DashboardTutorialsNewRoute,
  DashboardUsersUserIdRoute: DashboardUsersUserIdRoute,
  DashboardAuditLogsIndexRoute: DashboardAuditLogsIndexRoute,
  DashboardEventsIndexRoute: DashboardEventsIndexRoute,
  DashboardOrgsIndexRoute: DashboardOrgsIndexRoute,
  DashboardPostsIndexRoute: DashboardPostsIndexRoute,
  DashboardServicesIndexRoute: DashboardServicesIndexRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  DashboardTutorialsIndexRoute: DashboardTutorialsIndexRoute,
  DashboardUsersIndexRoute: DashboardUsersIndexRoute,
  DashboardEventsEventIdEditRoute: DashboardEventsEventIdEditRoute,
  DashboardOrgsOrgIdEditRoute: DashboardOrgsOrgIdEditRoute,
  DashboardPostsPostIdEditRoute: DashboardPostsPostIdEditRoute,
  DashboardServicesServiceIdEditRoute: DashboardServicesServiceIdEditRoute,
  DashboardServicesServiceIdFormBuilderRoute:
    DashboardServicesServiceIdFormBuilderRoute,
  DashboardTutorialsTutorialIdEditRoute: DashboardTutorialsTutorialIdEditRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface MySpaceRequestsRouteChildren {
  MySpaceRequestsRequestIdRoute: typeof MySpaceRequestsRequestIdRoute
  MySpaceRequestsRequestIdAppointmentRoute: typeof MySpaceRequestsRequestIdAppointmentRoute
}

const MySpaceRequestsRouteChildren: MySpaceRequestsRouteChildren = {
  MySpaceRequestsRequestIdRoute: MySpaceRequestsRequestIdRoute,
  MySpaceRequestsRequestIdAppointmentRoute:
    MySpaceRequestsRequestIdAppointmentRoute,
}

const MySpaceRequestsRouteWithChildren = MySpaceRequestsRoute._addFileChildren(
  MySpaceRequestsRouteChildren,
)

interface MySpaceRouteRouteChildren {
  MySpaceAssociationsRoute: typeof MySpaceAssociationsRoute
  MySpaceChildrenRoute: typeof MySpaceChildrenRoute
  MySpaceCompaniesRoute: typeof MySpaceCompaniesRoute
  MySpaceCvRoute: typeof MySpaceCvRoute
  MySpaceIboiteRoute: typeof MySpaceIboiteRoute
  MySpaceNotificationsRoute: typeof MySpaceNotificationsRoute
  MySpaceRequestsRoute: typeof MySpaceRequestsRouteWithChildren
  MySpaceSettingsRoute: typeof MySpaceSettingsRoute
  MySpaceVaultRoute: typeof MySpaceVaultRoute
  MySpaceIndexRoute: typeof MySpaceIndexRoute
  MySpaceAppointmentsBookRoute: typeof MySpaceAppointmentsBookRoute
  MySpaceAppointmentsNewRoute: typeof MySpaceAppointmentsNewRoute
  MySpaceAssociationsSlugRoute: typeof MySpaceAssociationsSlugRoute
  MySpaceCompaniesIdRoute: typeof MySpaceCompaniesIdRoute
  MySpaceProfileEditRoute: typeof MySpaceProfileEditRoute
  MySpaceAppointmentsIndexRoute: typeof MySpaceAppointmentsIndexRoute
  MySpaceProfileIndexRoute: typeof MySpaceProfileIndexRoute
  MySpaceServicesIndexRoute: typeof MySpaceServicesIndexRoute
  MySpaceServicesSlugNewRoute: typeof MySpaceServicesSlugNewRoute
}

const MySpaceRouteRouteChildren: MySpaceRouteRouteChildren = {
  MySpaceAssociationsRoute: MySpaceAssociationsRoute,
  MySpaceChildrenRoute: MySpaceChildrenRoute,
  MySpaceCompaniesRoute: MySpaceCompaniesRoute,
  MySpaceCvRoute: MySpaceCvRoute,
  MySpaceIboiteRoute: MySpaceIboiteRoute,
  MySpaceNotificationsRoute: MySpaceNotificationsRoute,
  MySpaceRequestsRoute: MySpaceRequestsRouteWithChildren,
  MySpaceSettingsRoute: MySpaceSettingsRoute,
  MySpaceVaultRoute: MySpaceVaultRoute,
  MySpaceIndexRoute: MySpaceIndexRoute,
  MySpaceAppointmentsBookRoute: MySpaceAppointmentsBookRoute,
  MySpaceAppointmentsNewRoute: MySpaceAppointmentsNewRoute,
  MySpaceAssociationsSlugRoute: MySpaceAssociationsSlugRoute,
  MySpaceCompaniesIdRoute: MySpaceCompaniesIdRoute,
  MySpaceProfileEditRoute: MySpaceProfileEditRoute,
  MySpaceAppointmentsIndexRoute: MySpaceAppointmentsIndexRoute,
  MySpaceProfileIndexRoute: MySpaceProfileIndexRoute,
  MySpaceServicesIndexRoute: MySpaceServicesIndexRoute,
  MySpaceServicesSlugNewRoute: MySpaceServicesSlugNewRoute,
}

const MySpaceRouteRouteWithChildren = MySpaceRouteRoute._addFileChildren(
  MySpaceRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  MySpaceRouteRoute: MySpaceRouteRouteWithChildren,
  AccessibiliteRoute: AccessibiliteRoute,
  CommunityRoute: CommunityRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  FaqRoute: FaqRoute,
  FormulairesRoute: FormulairesRoute,
  InformationRoute: InformationRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  PostLoginRedirectRoute: PostLoginRedirectRoute,
  TarifsRoute: TarifsRoute,
  AcademySlugRoute: AcademySlugRoute,
  NewsSlugRoute: NewsSlugRoute,
  OrgsSlugRoute: OrgsSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
  VerifyTokenRoute: VerifyTokenRoute,
  AcademyIndexRoute: AcademyIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
  OrgsIndexRoute: OrgsIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
